/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package UI;

import DAO.Impl.TrabajadorDAOImpl;
import DAO.Impl.UtilComprasDAOImpl;
import DAO.Impl.UtilVentasDAOImpl;
import DAO.UtilComprasDAO;
import DAO.UtilVentasDAO;
import UI.internal.InFrmCliente;
import UI.internal.InFrmCorreo;
import UI.internal.InFrmTienda;
import UI.internal.InFrmTrabajador;
import UI.internal.InFrmVenta;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.util.HashMap;
import java.util.Map;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JMenuItem;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperExportManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author xhesm
 */
public class FrmPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form FrmPrincipal
     */
    public static int ID_USUARIO_SESION;
    public static String DATA_USUARIO_SESION;
    public static String DATA_SQL;
    public static String DATA_ROL;

    UtilComprasDAO comprasDAO = new UtilComprasDAOImpl();
    UtilVentasDAO ventasDAO = new UtilVentasDAOImpl();

    public FrmPrincipal() {
        initComponents();
        centerFrameOnScreen(this);
        this.setExtendedState(JFrame.MAXIMIZED_BOTH);
        this.lbluser.setText(DATA_USUARIO_SESION);
        validaciondeMenusPorRol(FrmPrincipal.DATA_ROL);
    }

    private void validaciondeMenusPorRol(String rol) {
        desactivar(mnalmacen,
                mncliente,
                mncompra,
                mncorreo,
                mnproductos,
                mnproveedor,
                mntienda,
                mntrabajador,
                mnusuario,
                mnventa,
                mnventasXtrabajador);
        switch (rol) {
            case "Vendedor": {
                activar(
                        mncliente,
                        mncompra,
                        mnproductos,
                        mnproveedor,
                        mncorreo,
                        mntienda,
                        mnventa,
                        mnventasXtrabajador);
            }
            break;
            case "Admin": {
                activar(mnalmacen,
                        mncliente,
                        mncompra,
                        mncorreo,
                        mnproductos,
                        mnproveedor,
                        mntienda,
                        mntrabajador,
                        mnusuario,
                        mnventa,
                        mnventasXtrabajador);

            }
            break;
            default:
                throw new AssertionError();
        }
    }

    private void activar(JMenuItem... items) {
        for (JMenuItem mn : items) {
            mn.setVisible(true);
        }
    }

    private void desactivar(JMenuItem... items) {
        for (JMenuItem mn : items) {
            mn.setVisible(false);
        }
    }

    private static void centerFrameOnScreen(JFrame frame) {
        Dimension screenSize = Toolkit.getDefaultToolkit().getScreenSize();
        int centerX = (int) (screenSize.getWidth() - frame.getWidth()) / 2;
        int centerY = (int) (screenSize.getHeight() - frame.getHeight()) / 2;
        frame.setLocation(centerX, centerY);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        desktop = new javax.swing.JDesktopPane();
        jPanel1 = new javax.swing.JPanel();
        lblserver = new javax.swing.JLabel();
        lbluser = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu3 = new javax.swing.JMenu();
        mncompra = new javax.swing.JMenuItem();
        mnventa = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        mnproveedor = new javax.swing.JMenuItem();
        mncliente = new javax.swing.JMenuItem();
        mntrabajador = new javax.swing.JMenuItem();
        mnproductos = new javax.swing.JMenuItem();
        mnalmacen = new javax.swing.JMenuItem();
        mnusuario = new javax.swing.JMenuItem();
        mntienda = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        mncompras = new javax.swing.JMenuItem();
        mnventasXtrabajador = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        mncorreo = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        desktop.setBackground(new java.awt.Color(204, 255, 204));

        javax.swing.GroupLayout desktopLayout = new javax.swing.GroupLayout(desktop);
        desktop.setLayout(desktopLayout);
        desktopLayout.setHorizontalGroup(
            desktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 815, Short.MAX_VALUE)
        );
        desktopLayout.setVerticalGroup(
            desktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 425, Short.MAX_VALUE)
        );

        lblserver.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICONS/Microsoft SQL Server.png"))); // NOI18N
        lblserver.setText("localhost:1433");
        lblserver.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblserverMouseClicked(evt);
            }
        });

        lbluser.setText("Administrador / Usuario");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(lblserver)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lbluser)
                .addGap(14, 14, 14))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblserver)
                    .addComponent(lbluser))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jMenu3.setText("Transacciones");

        mncompra.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICONS/Return Purchase.png"))); // NOI18N
        mncompra.setText("Compra");
        jMenu3.add(mncompra);

        mnventa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICONS/Checkout.png"))); // NOI18N
        mnventa.setText("Venta");
        mnventa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnventaActionPerformed(evt);
            }
        });
        jMenu3.add(mnventa);

        jMenuBar1.add(jMenu3);

        jMenu2.setText("Mantenimientos");

        mnproveedor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICONS/Escrow Process.png"))); // NOI18N
        mnproveedor.setText("Proveedor");
        jMenu2.add(mnproveedor);

        mncliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICONS/User Male_1.png"))); // NOI18N
        mncliente.setText("Cliente");
        mncliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnclienteActionPerformed(evt);
            }
        });
        jMenu2.add(mncliente);

        mntrabajador.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICONS/Collaborator Male Skin Type 2.png"))); // NOI18N
        mntrabajador.setText("Trabajador");
        mntrabajador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mntrabajadorActionPerformed(evt);
            }
        });
        jMenu2.add(mntrabajador);

        mnproductos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICONS/Box.png"))); // NOI18N
        mnproductos.setText("Productos");
        jMenu2.add(mnproductos);

        mnalmacen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICONS/Warehouse.png"))); // NOI18N
        mnalmacen.setText("Almacén");
        jMenu2.add(mnalmacen);

        mnusuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICONS/User Male.png"))); // NOI18N
        mnusuario.setText("Usuario");
        jMenu2.add(mnusuario);

        mntienda.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICONS/Small Business.png"))); // NOI18N
        mntienda.setText("Tienda");
        mntienda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mntiendaActionPerformed(evt);
            }
        });
        jMenu2.add(mntienda);

        jMenuBar1.add(jMenu2);

        jMenu1.setText("Reportes");

        mncompras.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICONS/Document.png"))); // NOI18N
        mncompras.setText("Compras");
        mncompras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mncomprasActionPerformed(evt);
            }
        });
        jMenu1.add(mncompras);

        mnventasXtrabajador.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICONS/Business Report.png"))); // NOI18N
        mnventasXtrabajador.setText("Ventas por Trabajador");
        mnventasXtrabajador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnventasXtrabajadorActionPerformed(evt);
            }
        });
        jMenu1.add(mnventasXtrabajador);

        jMenuBar1.add(jMenu1);

        jMenu4.setText("Herramientas");

        mncorreo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICONS/Letter.png"))); // NOI18N
        mncorreo.setText("Correo");
        mncorreo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mncorreoActionPerformed(evt);
            }
        });
        jMenu4.add(mncorreo);

        jMenuBar1.add(jMenu4);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktop)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(desktop)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mntrabajadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mntrabajadorActionPerformed
        // TODO add your handling code here:
        InFrmTrabajador frmTrabajador = new InFrmTrabajador();
        desktop.add(frmTrabajador);
        frmTrabajador.setVisible(true);
        frmTrabajador.setLocation(200, 100);
    }//GEN-LAST:event_mntrabajadorActionPerformed

    private void lblserverMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblserverMouseClicked
        // TODO add your handling code here:
        new FrmConfig().setVisible(true);
    }//GEN-LAST:event_lblserverMouseClicked

    private void mntiendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mntiendaActionPerformed
        // TODO add your handling code here: 
        InFrmTienda frmTienda = new InFrmTienda();
        desktop.add(frmTienda);
        frmTienda.setVisible(true);
        frmTienda.setLocation(200, 100);
    }//GEN-LAST:event_mntiendaActionPerformed

    private void mncomprasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mncomprasActionPerformed
        // TODO add your handling code here: 
        comprasDAO.ImprimirReporte();
    }//GEN-LAST:event_mncomprasActionPerformed

    private void mnventasXtrabajadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnventasXtrabajadorActionPerformed
        // TODO add your handling code here:
        ventasDAO.ImprimirReporte();
    }//GEN-LAST:event_mnventasXtrabajadorActionPerformed

    private void mncorreoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mncorreoActionPerformed
        // TODO add your handling code here: 
        InFrmCorreo frmCorreo = new InFrmCorreo();
        desktop.add(frmCorreo);
        frmCorreo.setVisible(true);
        frmCorreo.setLocation(200, 100);
    }//GEN-LAST:event_mncorreoActionPerformed

    private void mnventaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnventaActionPerformed
        // TODO add your handling code here:
        InFrmVenta frmVenta = new InFrmVenta();
        desktop.add(frmVenta);
        frmVenta.setVisible(true);
        frmVenta.setLocation(200, 100);

    }//GEN-LAST:event_mnventaActionPerformed

    private void mnclienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnclienteActionPerformed
        // TODO add your handling code here:

        InFrmCliente frmCliente = new InFrmCliente();
        desktop.add(frmCliente);
        frmCliente.setVisible(true);
        frmCliente.setLocation(200, 100);
    }//GEN-LAST:event_mnclienteActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane desktop;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    public static javax.swing.JLabel lblserver;
    private javax.swing.JLabel lbluser;
    private javax.swing.JMenuItem mnalmacen;
    private javax.swing.JMenuItem mncliente;
    private javax.swing.JMenuItem mncompra;
    private javax.swing.JMenuItem mncompras;
    private javax.swing.JMenuItem mncorreo;
    private javax.swing.JMenuItem mnproductos;
    private javax.swing.JMenuItem mnproveedor;
    private javax.swing.JMenuItem mntienda;
    private javax.swing.JMenuItem mntrabajador;
    private javax.swing.JMenuItem mnusuario;
    private javax.swing.JMenuItem mnventa;
    private javax.swing.JMenuItem mnventasXtrabajador;
    // End of variables declaration//GEN-END:variables
}
