/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package UI.internal;

import BEAN.ComboData;
import BEAN.Tienda;
import BEAN.Trabajador;
import DAO.Impl.TiendaDAOImpl;
import DAO.TiendaDAO;
import java.text.SimpleDateFormat;
import java.time.LocalDate;
import java.time.ZoneId;
import java.time.format.DateTimeFormatter;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.Enumeration;
import java.util.List;
import javax.swing.AbstractButton;
import javax.swing.ButtonGroup;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;
import javax.swing.table.DefaultTableModel;
import javax.swing.text.DateFormatter;

/**
 *
 * @author xhesm
 */
public class InFrmTienda extends javax.swing.JInternalFrame {

    /**
     * Creates new form InFrmTrabajador
     */
    TiendaDAO tiendaDAO = new TiendaDAOImpl();

    DefaultTableModel defaultTableModel = new DefaultTableModel();
    Object[][] select, selectaux;
    //DefaultComboBoxModel<ComboData> boxModel = null;

    public InFrmTienda() {
        initComponents();
        this.setTitle("Tienda");
        this.setClosable(true);
        this.setResizable(true);
        this.txtBuscador.setEnabled(false);
        ///defaultTableModel = tiendaDAO.llenartabla();
        //select = tiendaDAO.select();
        //selectaux = select;
        //defaultTableModel.setDataVector(select, new Object[]{"idTrabajador", "Puesto", "Nro Documento", "Nombre", "Apellido Paterno", "Apellido Materno", "Ubigeo", "Direccion", "Genero", "Fecha Nacimiento", "Celular", "Telefono", "Correo", "Estado"});
        jbtlTienda.setModel(tiendaDAO.llenartabla());
        //  boxModel = tiendaDAO.llenarcombo();

    }

    void setDataTienda(Tienda tienda) {
        txtid.setText(tienda.getIdTienda() + "");
        txtDescripcion.setText(tienda.getDescr());
        txtNameTienda.setText(tienda.getTienda());
        txtUbigeo.setText(tienda.getIdUbigeo() + "");
        if (tienda.getIdEstado() == 1) {
            rbActivo.setSelected(true);
        } else {
            rbInactivo.setSelected(true);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnGrpEstado = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        txtDescripcion = new javax.swing.JTextField();
        txtid = new javax.swing.JTextField();
        txtUbigeo = new javax.swing.JTextField();
        txtNameTienda = new javax.swing.JTextField();
        rbActivo = new javax.swing.JRadioButton();
        rbInactivo = new javax.swing.JRadioButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        btnNuevo = new javax.swing.JButton();
        btnregistro = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jbtlTienda = new javax.swing.JTable();
        txtBuscador = new javax.swing.JTextField();
        cboBuscar = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));
        getContentPane().setLayout(new javax.swing.BoxLayout(getContentPane(), javax.swing.BoxLayout.PAGE_AXIS));

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Tienda"));

        txtid.setEnabled(false);

        btnGrpEstado.add(rbActivo);
        rbActivo.setText("Activo");
        rbActivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbActivoActionPerformed(evt);
            }
        });

        btnGrpEstado.add(rbInactivo);
        rbInactivo.setText("Inactivo");
        rbInactivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbInactivoActionPerformed(evt);
            }
        });

        jLabel1.setText("Id");

        jLabel4.setText("Descripción");

        jLabel7.setText("Ubigeo");

        jLabel9.setText("Nombre de Tienda");

        btnNuevo.setText("Nuevo");
        btnNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevoActionPerformed(evt);
            }
        });

        btnregistro.setText("Registrar");
        btnregistro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnregistroActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtid, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel7)
                                    .addComponent(txtUbigeo, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(116, 116, 116)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtDescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel4)
                                    .addComponent(txtNameTienda, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel9)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(rbActivo)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(rbInactivo)))))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnNuevo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnregistro)
                        .addGap(0, 365, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNameTienda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(2, 2, 2)
                        .addComponent(txtDescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addGap(4, 4, 4)
                        .addComponent(txtUbigeo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbActivo)
                    .addComponent(rbInactivo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnNuevo)
                    .addComponent(btnregistro))
                .addGap(18, 18, 18))
        );

        getContentPane().add(jPanel1);

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jbtlTienda.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jbtlTienda.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jbtlTienda.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbtlTienda.setGridColor(new java.awt.Color(102, 204, 0));
        jbtlTienda.setRowHeight(15);
        jbtlTienda.setRowMargin(1);
        jbtlTienda.setSelectionBackground(new java.awt.Color(102, 204, 0));
        jbtlTienda.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jbtlTienda.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jbtlTiendaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jbtlTienda);

        cboBuscar.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "TODOS", "NOMBRE", "UBIGEO", "DESCRIPCION" }));
        cboBuscar.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cboBuscarItemStateChanged(evt);
            }
        });

        jButton1.setText("Buscar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 543, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(cboBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtBuscador)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton1)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtBuscador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cboBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 283, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel2);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevoActionPerformed
        limpiar();
    }//GEN-LAST:event_btnNuevoActionPerformed

    void limpiar() {
        txtBuscador.setText("");
        txtid.setText("");
        txtNameTienda.setText("");
        txtUbigeo.setText("");
        txtDescripcion.setText("");
        btnregistro.setText("Registrar");
    }

    private static String getSelectedButtonValue(ButtonGroup buttonGroup) {
        for (Enumeration<AbstractButton> buttons = buttonGroup.getElements(); buttons.hasMoreElements();) {
            AbstractButton button = buttons.nextElement();
            if (button.isSelected()) {
                return button.getText();
            }
        }

        return null;
    }

    private void btnregistroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnregistroActionPerformed
        // TODO add your handling code here:
        Tienda t = new Tienda();
        t.setTienda(txtNameTienda.getText());
        t.setIdEstado((short) (rbActivo.isSelected() ? 1 : 0));
        t.setDescr(txtDescripcion.getText());
        t.setIdUbigeo(txtUbigeo.getText());

        System.out.println(this.btnregistro.getText());
        switch (this.btnregistro.getText()) {
            case "Registrar":
                t.setIdTienda(0);
                if (tiendaDAO.save(t)) {
                    JOptionPane.showMessageDialog(this, "Tienda Guardado Correctamete", "Mensaje de confirmación", JOptionPane.INFORMATION_MESSAGE);
                    jbtlTienda.setModel(tiendaDAO.llenartabla());
                }
                break;
            case "Actualizar":
                t.setIdTienda(Integer.parseInt(txtid.getText()));
                if (tiendaDAO.save(t)) {
                    JOptionPane.showMessageDialog(this, "Tienda Actualizada Correctamete", "Mensaje de confirmación", JOptionPane.INFORMATION_MESSAGE);
                    jbtlTienda.setModel(tiendaDAO.llenartabla());
                }
                break;
        }

    }//GEN-LAST:event_btnregistroActionPerformed


    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here: 
        String buscar = cboBuscar.getSelectedItem().toString();
        switch (buscar) {
            case "TODOS":
                defaultTableModel = tiendaDAO.llenartabla();
                break;
            case "NOMBRE":
                defaultTableModel = tiendaDAO.buscarEnTabla("Tienda", txtBuscador.getText());
                break;
            case "UBIGEO":
                defaultTableModel = tiendaDAO.buscarEnTabla("idUbigeo", txtBuscador.getText());
                break;
            case "DESCRIPCION":
                defaultTableModel = tiendaDAO.buscarEnTabla("descr", txtBuscador.getText());
                break;
            default:
                throw new AssertionError();
        }
        jbtlTienda.setModel(defaultTableModel);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void cboBuscarItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cboBuscarItemStateChanged
        // TODO add your handling code here: 
        String str = this.cboBuscar.getSelectedItem().toString();
        if (str.equals("TODOS")) {
            txtBuscador.setEnabled(false);
        } else {
            txtBuscador.setEnabled(true);
        }
    }//GEN-LAST:event_cboBuscarItemStateChanged

    private static int findIndex(DefaultComboBoxModel<ComboData> model, ComboData value) {
        for (int i = 0; i < model.getSize(); i++) {
            if (model.getElementAt(i).getId() == (value.getId())) {
                return i;
            }
        }
        return -1;
    }

    private void jbtlTiendaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbtlTiendaMouseClicked

        int selectedRow = jbtlTienda.getSelectedRow();

        if (selectedRow != -1) {
            // Obtener datos de la fila seleccionada
            int idTienda = Integer.parseInt((String) jbtlTienda.getValueAt(selectedRow, 0));
            String nombre = (String) jbtlTienda.getValueAt(selectedRow, 1);
            String idUbigeo = jbtlTienda.getValueAt(selectedRow, 2).toString().trim();
            String descripcion = (String) jbtlTienda.getValueAt(selectedRow, 3);
            DateTimeFormatter formatter = DateTimeFormatter.ofPattern("yyyy-MM-dd");
            short estado = (short) (("Activo".equals(jbtlTienda.getValueAt(selectedRow, 4).toString())) ? 1 : 0);
            Tienda t = new Tienda(idTienda, nombre, idUbigeo, descripcion, estado);
            btnregistro.setText("Actualizar");
            setDataTienda(t);
        }

    }//GEN-LAST:event_jbtlTiendaMouseClicked

    private void rbActivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbActivoActionPerformed
        // TODO add your handling code here:
        String selectedValue = getSelectedButtonValue(btnGrpEstado);
        System.out.println(selectedValue);
    }//GEN-LAST:event_rbActivoActionPerformed

    private void rbInactivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbInactivoActionPerformed
        // TODO add your handling code here:
        String selectedValue = getSelectedButtonValue(btnGrpEstado);
        System.out.println(selectedValue);
    }//GEN-LAST:event_rbInactivoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup btnGrpEstado;
    private javax.swing.JButton btnNuevo;
    private javax.swing.JButton btnregistro;
    private javax.swing.JComboBox<String> cboBuscar;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jbtlTienda;
    private javax.swing.JRadioButton rbActivo;
    private javax.swing.JRadioButton rbInactivo;
    private javax.swing.JTextField txtBuscador;
    private javax.swing.JTextField txtDescripcion;
    private javax.swing.JTextField txtNameTienda;
    private javax.swing.JTextField txtUbigeo;
    private javax.swing.JTextField txtid;
    // End of variables declaration//GEN-END:variables
}
