package UI.internal;

import BEAN.CabCompra;
import BEAN.Categoria;
import BEAN.DetCompra;
import BEAN.Producto;
import BEAN.Proveedor;
import BEAN.TipoComprobante;
import DAO.Impl.CabCompraDAO;
import DAO.Impl.CategoriaDAO;
import DAO.Impl.DetCompraDAO;
import DAO.Impl.TipoComprobanteDAO;
import DAO.Util;
import UI.SelProducto;
import UTIL.EmailOnlyDocument;
import UTIL.NumberOnlyDocument;
import UTIL.TextOnlyDocument;
import java.text.DecimalFormat;
import java.text.SimpleDateFormat;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

public class InFrmCompra extends javax.swing.JInternalFrame {

    DefaultTableModel dtm1;
    CabCompraDAO cabDAO;
    DetCompraDAO detDAO;
    Util u;
    TipoComprobanteDAO tipCompDAO;
    CategoriaDAO catDAO;
    int idCompra;
    DecimalFormat formatDec;
    SimpleDateFormat formatoFechaE;
    String fechaEmision = "";

    public InFrmCompra() {
        initComponents();
        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setClosable(true);
        u = new Util();
        dtm1 = (DefaultTableModel) this.TBLdetCompra.getModel();

        cabDAO = new CabCompraDAO();
        detDAO = new DetCompraDAO();

        catDAO = new CategoriaDAO();
        tipCompDAO = new TipoComprobanteDAO();

        formatDec = new DecimalFormat("#.00");
        formatoFechaE = new SimpleDateFormat("yyyy-MM-dd hh:mm:ss");
        this.llenaCmbTipoComprobante(false, "");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton3 = new javax.swing.JButton();
        JPFormCompra = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        txtIdProd = new javax.swing.JTextField();
        txtPrecioProd = new javax.swing.JTextField();
        txtCantProd = new javax.swing.JTextField();
        txtCatProd = new javax.swing.JTextField();
        txtDescuentoProd = new javax.swing.JTextField();
        txtImporte = new javax.swing.JTextField();
        txtNombProd = new javax.swing.JTextField();
        BtnAgregar = new javax.swing.JButton();
        Totalizar = new javax.swing.JButton();
        btnBuscarProd = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        calFecha = new com.toedter.calendar.JDateChooser();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        CmbTipoComp = new javax.swing.JComboBox<>();
        txtSerie = new javax.swing.JTextField();
        txtCorrelativo = new javax.swing.JTextField();
        txtSubTotal = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtIGV = new javax.swing.JTextField();
        txtTotal = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        txtIdProveedor = new javax.swing.JTextField();
        txtNifProveedor = new javax.swing.JTextField();
        txtProveedor = new javax.swing.JTextField();
        BtnBuscarProveedor = new javax.swing.JButton();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TBLdetCompra = new javax.swing.JTable();
        LimpiarBTN = new javax.swing.JButton();
        GrabarBTN = new javax.swing.JButton();

        jButton3.setText("jButton2");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        JPFormCompra.setBorder(javax.swing.BorderFactory.createTitledBorder("Compra"));
        JPFormCompra.setToolTipText("");

        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel10.setText("ID");

        txtIdProd.setEnabled(false);
        txtIdProd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIdProdActionPerformed(evt);
            }
        });

        txtPrecioProd.setEnabled(false);
        txtPrecioProd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPrecioProdActionPerformed(evt);
            }
        });

        txtCatProd.setEnabled(false);

        txtImporte.setEnabled(false);

        txtNombProd.setEnabled(false);

        BtnAgregar.setText("Agregar");
        BtnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnAgregarActionPerformed(evt);
            }
        });

        Totalizar.setText("jButton2");
        Totalizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TotalizarActionPerformed(evt);
            }
        });

        btnBuscarProd.setText("Buscar");
        btnBuscarProd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarProdActionPerformed(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel11.setText("%");

        jLabel12.setText("Precio Unitario");

        jLabel13.setText("IMPORTE");

        jLabel14.setText("Descripción");

        jLabel15.setText("Categoría");

        jLabel16.setText("CANTIDAD");

        jLabel17.setText("DESCUENTO");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10)
                    .addComponent(jLabel14)
                    .addComponent(jLabel15))
                .addGap(42, 42, 42)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(txtNombProd, javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(txtIdProd, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(41, 41, 41)
                        .addComponent(jLabel12)
                        .addGap(27, 27, 27)
                        .addComponent(txtPrecioProd, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(txtCatProd))
                .addGap(58, 58, 58)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel16)
                    .addComponent(jLabel17)
                    .addComponent(jLabel13))
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(txtImporte, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(txtDescuentoProd, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(Totalizar, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnBuscarProd)
                                .addGap(54, 54, 54))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(txtCantProd, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(BtnAgregar, javax.swing.GroupLayout.PREFERRED_SIZE, 889, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(txtIdProd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCantProd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel16)
                    .addComponent(jLabel12)
                    .addComponent(txtPrecioProd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNombProd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14)
                    .addComponent(txtDescuentoProd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel17)
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBuscarProd))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel13, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtCatProd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel15)
                        .addComponent(txtImporte, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(Totalizar)))
                .addGap(26, 26, 26)
                .addComponent(BtnAgregar)
                .addGap(15, 15, 15))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel2.setText("Fecha");

        jLabel3.setText("Tipo Comprobante");

        jLabel4.setText("Cajero");

        jLabel5.setText("Nro de Doc");

        CmbTipoComp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CmbTipoCompActionPerformed(evt);
            }
        });

        txtSerie.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSerieActionPerformed(evt);
            }
        });

        txtCorrelativo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCorrelativoActionPerformed(evt);
            }
        });

        txtSubTotal.setEnabled(false);

        jLabel7.setText("IGV");

        txtIGV.setEnabled(false);

        txtTotal.setEnabled(false);
        txtTotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTotalActionPerformed(evt);
            }
        });

        jLabel8.setText("TOTAL");

        jLabel6.setText("SUB TOTAL");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(34, 34, 34)
                        .addComponent(calFecha, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(18, 18, 18)
                        .addComponent(CmbTipoComp, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel5)
                    .addComponent(jLabel4))
                .addGap(26, 26, 26)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                        .addComponent(txtSerie, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtCorrelativo))
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8))
                .addGap(40, 40, 40)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtIGV, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtSubTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(38, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(calFecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel4)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtSubTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel6)))
                .addGap(22, 22, 22)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtSerie, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCorrelativo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(txtIGV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CmbTipoComp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(21, 21, 21)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addContainerGap(39, Short.MAX_VALUE))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel9.setText("Nombre");

        txtIdProveedor.setEnabled(false);

        txtNifProveedor.setEnabled(false);

        txtProveedor.setEnabled(false);

        BtnBuscarProveedor.setText("Buscar");
        BtnBuscarProveedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnBuscarProveedorActionPerformed(evt);
            }
        });

        jLabel18.setText("ID");

        jLabel19.setText("NIF");

        jLabel1.setText("Proveedor");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtIdProveedor, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel18))
                .addGap(78, 78, 78)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtNifProveedor, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel19))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(txtProveedor, javax.swing.GroupLayout.PREFERRED_SIZE, 374, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(BtnBuscarProveedor)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(32, 32, 32))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel18)
                            .addComponent(jLabel19)
                            .addComponent(jLabel9))
                        .addGap(9, 9, 9)))
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNifProveedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtIdProveedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtProveedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BtnBuscarProveedor))
                .addContainerGap(19, Short.MAX_VALUE))
        );

        TBLdetCompra.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "IdProducto", "Descripción", "Precio", "Cantidad", "Descuento"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(TBLdetCompra);

        javax.swing.GroupLayout JPFormCompraLayout = new javax.swing.GroupLayout(JPFormCompra);
        JPFormCompra.setLayout(JPFormCompraLayout);
        JPFormCompraLayout.setHorizontalGroup(
            JPFormCompraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPFormCompraLayout.createSequentialGroup()
                .addGroup(JPFormCompraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(JPFormCompraLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(JPFormCompraLayout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addGroup(JPFormCompraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );
        JPFormCompraLayout.setVerticalGroup(
            JPFormCompraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPFormCompraLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        LimpiarBTN.setText("Nueva Compra");
        LimpiarBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LimpiarBTNActionPerformed(evt);
            }
        });

        GrabarBTN.setText("Generar Compra");
        GrabarBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GrabarBTNActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(LimpiarBTN)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(GrabarBTN)
                        .addGap(25, 25, 25))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(JPFormCompra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(JPFormCompra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LimpiarBTN)
                    .addComponent(GrabarBTN))
                .addContainerGap(25, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CmbTipoCompActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CmbTipoCompActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CmbTipoCompActionPerformed

    private void txtSerieActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSerieActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSerieActionPerformed

    private void txtCorrelativoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCorrelativoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCorrelativoActionPerformed

    private void txtTotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTotalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTotalActionPerformed

    private void txtIdProdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIdProdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIdProdActionPerformed

    private void txtPrecioProdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPrecioProdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPrecioProdActionPerformed

    private void btnBuscarProdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarProdActionPerformed
        Producto p;
        String categ;
        SelProducto dialog = new SelProducto(new javax.swing.JFrame(), true);
        dialog.setVisible(true);
        p = dialog.devProd();
        this.txtIdProd.setText(String.valueOf(p.getIdProducto()));
        this.txtNombProd.setText(p.getDescr());
        this.txtPrecioProd.setText(String.valueOf(p.getPrecVta()));
        categ = this.llenaTxtCategoria(true, String.valueOf(p.getIdCategoria()));
        this.txtCatProd.setText(llenaTxtCategoria(true, String.valueOf(categ)));
        this.txtDescuentoProd.setText("0");
    }//GEN-LAST:event_btnBuscarProdActionPerformed

    private String llenaTxtCategoria(boolean sw, String cad) {
        String c = "";
        Vector<Categoria> listaCate;
        listaCate = catDAO.listaCategoria(sw, cad);
        for (int i = 0; i < listaCate.size(); i++) {

            if (sw == true) {
                c = listaCate.get(i).getDescr();
            }
        }
        return c;
    }

    private String llenaCmbTipoComprobante(boolean sw, String cad) {
        String t = "";
        Vector<TipoComprobante> listaTipoComp;
        listaTipoComp = tipCompDAO.listaTipoComprobante(sw, cad);
        this.CmbTipoComp.addItem("");
        for (int i = 0; i < listaTipoComp.size(); i++) {
            this.CmbTipoComp.addItem(listaTipoComp.get(i).getDescr());
            if (sw == true) {
                t = listaTipoComp.get(i).getDescr();
            }
        }

        return t;

    }

    private boolean validaDatos() {
        boolean aux = false;
        String cad = "";
        if (this.calFecha.getDate() == null) {
            cad = "\nSeleccione la fecha de compra";
        }
        if (this.CmbTipoComp.getSelectedItem().toString().equals("")) {
            cad += "\nSeleccione el tipo de documento";
        }
        if (this.txtSerie.getText().equals("")) {
            cad += "\nIngrese el número de serie del documento";
        }
        if (this.txtCorrelativo.getText().equals("")) {
            cad += "\nIngrese el número de correlativo del documento";
        }
        if (this.txtIdProveedor.getText().equals("")) {
            cad += "\nSeleccione el proveedor";
        }
        if (dtm1.getRowCount() == 0) {
            cad += "\nRegistre el detalle de la compra";
        }
        if (cad != "") {
            JOptionPane.showMessageDialog(this, cad);
        }
        return aux = true;
    }


    private void BtnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnAgregarActionPerformed
        if (this.txtIdProd.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Debe seleccionar un producto");
        } else if (this.txtCantProd.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Debe ingresar una cantidad");
        } else {
            boolean validPorc, validCant;
            validPorc = validaImportes("porc", Double.parseDouble(this.txtDescuentoProd.getText()));
            validCant = validaImportes("cant", Double.parseDouble(this.txtCantProd.getText()));
            if (validPorc == false) {
                JOptionPane.showMessageDialog(this, "Descuento inválido,máximo a aplicar: 20%");
            }
            if (validCant == false) {
                JOptionPane.showMessageDialog(this, "Cantidad inválida");
            } else {
                Vector vec = new Vector();
                vec.addElement(this.txtIdProd.getText());
                vec.addElement(this.txtNombProd.getText());
                vec.addElement(this.txtPrecioProd.getText());
                vec.addElement(this.txtCantProd.getText());
                vec.addElement(this.txtDescuentoProd.getText());
                this.dtm1.addRow(vec);
                limpiaProducto();

                this.TotalCompra();
            }

        }
    }//GEN-LAST:event_BtnAgregarActionPerformed

    private void TotalCompra() {
        double precio, cantidad, descuento, subtotal = 0, total, impuesto;

        for (int i = 0; i < dtm1.getRowCount(); i++) {
            precio = Double.parseDouble(dtm1.getValueAt(i, 2).toString().replace(",", "."));
            cantidad = Double.parseDouble(dtm1.getValueAt(i, 3).toString().replace(",", "."));

            if (dtm1.getValueAt(i, 4).toString().isEmpty()) {
                descuento = 0.0;
            } else {
                descuento = Double.parseDouble(dtm1.getValueAt(i, 4).toString().replace(",", "."));
            }

            subtotal = subtotal + precio * cantidad * (100 - descuento) / 100;
        }
        impuesto = subtotal * 0.18;
        total = subtotal + impuesto;

        // Asegúrate de que txtIGV y txtTotal no contengan comas antes de intentar convertirlos a double
        this.txtIGV.setText(formatDec.format(impuesto).replace(",", "."));
        this.txtTotal.setText(formatDec.format(total).replace(",", "."));

        this.txtSubTotal.setText(formatDec.format(subtotal));
    }

    private void limpiaProducto() {
        this.txtIdProd.setText("");
        this.txtNombProd.setText("");
        this.txtPrecioProd.setText("");
        this.txtCantProd.setText("");
        this.txtDescuentoProd.setText("");
        this.txtCatProd.setText("");
        this.txtImporte.setText("");
    }

    private void guardarCompraEnBaseDeDatos() {
        if (validaDatos()) {
            u = new Util();
            // Grabar Cabecera de Compra
            CabCompra cc = new CabCompra();
            idCompra = u.idNext("CabCompra", "idCompra");
            cc.setIdCompra(idCompra);
            cc.setIdProveedor(Integer.parseInt(this.txtIdProveedor.getText()));
            cc.setIdTipComp(codigoTipoComprobante(true, this.CmbTipoComp.getSelectedItem().toString()));
            cc.setSerie(this.txtSerie.getText());
            cc.setCorrelativo(this.txtCorrelativo.getText());

            fechaEmision = formatoFechaE.format(this.calFecha.getCalendar().getTime());
            cc.setFecha(fechaEmision);

            cc.setImpuesto(Double.parseDouble(this.txtIGV.getText()));
            cc.setTotal(Double.parseDouble(this.txtTotal.getText()));
            cc.setIdUsuarioReg(101); // por revisar
            cc.setIdUsuarioMod(101); // por revisar
            cc.setFechReg(u.obtenerFecha());
            cc.setFechaMod(u.obtenerFecha());
            cc.setEstado(1);

            this.cabDAO.procesaCabCompra(cc, "insertar");

            // Grabando en detCompra
            int linea = 1;
            for (int i = 0; i < dtm1.getRowCount(); i++) {
                DetCompra dv = new DetCompra();
                dv.setIdCompra(idCompra);
                dv.setIdDetCompra(linea);
                dv.setIdProducto(Integer.parseInt(dtm1.getValueAt(i, 0).toString()));
                dv.setCantidad(Double.parseDouble(dtm1.getValueAt(i, 3).toString()));
                dv.setImporte(Double.parseDouble(dtm1.getValueAt(i, 2).toString()));
                dv.setDescuento(Double.parseDouble(dtm1.getValueAt(i, 4).toString()));
                this.detDAO.procesaDetCompra(dv, "insertar");
                linea += 1;
            }

            JOptionPane.showMessageDialog(this, "Compra Realizada con éxito");

            this.limpiaCompra();
            this.limpiaProducto();
            dtm1.setRowCount(0);
        }
    }

    private void limpiaCompra() {
        this.calFecha.setDate(null);
        this.CmbTipoComp.setSelectedItem("");
        this.txtSerie.setText("");
        this.txtCorrelativo.setText("");
        this.txtSubTotal.setText("");
        this.txtIGV.setText("");
        this.txtTotal.setText("");
        this.txtIdProveedor.setText("");
        this.txtNifProveedor.setText("");
        this.txtProveedor.setText("");
    }


    private void TotalizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TotalizarActionPerformed
        if (this.txtIdProd.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Seleccione producto");
        } else {
            boolean validPorc, validCant;
            double precio, cantidad, descuento;
            String total;

            validPorc = validaImportes("porc", Double.parseDouble(this.txtDescuentoProd.getText()));
            validCant = validaImportes("cant", Double.parseDouble(this.txtCantProd.getText()));
            if (validPorc == false) {
                JOptionPane.showMessageDialog(this, "Descuento inválido,máximo a aplicar: 20%");
            }
            if (validCant == false) {
                JOptionPane.showMessageDialog(this, "Cantidad inválida");
            } else {
                precio = Double.parseDouble(this.txtPrecioProd.getText());
                cantidad = Double.parseDouble(this.txtCantProd.getText());

                if (this.txtDescuentoProd.getText().equals("0")) {
                    descuento = 0;
                } else {
                    descuento = Double.parseDouble(this.txtDescuentoProd.getText());
                }

                total = formatDec.format(precio * cantidad * (100 - descuento) / 100);
                this.txtImporte.setText(String.valueOf(total));
            }
        }
    }//GEN-LAST:event_TotalizarActionPerformed

    private boolean validaImportes(String dato, Double val) {
        boolean aux = true;

        if (dato == "porc") {
            if (val < 0 || val > 20) {
                aux = false;
            }
        }
        if (dato == "cant") {
            if (val < 0) {
                aux = false;
            }
        }
        return aux;
    }

    private void LimpiarBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LimpiarBTNActionPerformed
        this.limpiaCompra();
        this.limpiaProducto();
        dtm1.setRowCount(0);
    }//GEN-LAST:event_LimpiarBTNActionPerformed
    public void default_validaciones() {
        txtCorrelativo.setDocument(new NumberOnlyDocument(11));
        txtCantProd.setDocument(new NumberOnlyDocument(3));
        txtSerie.setDocument(new NumberOnlyDocument(3));
        txtDescuentoProd.setDocument(new NumberOnlyDocument(2));
        jTextField1.setDocument(new TextOnlyDocument(20));
    }
    private void GrabarBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GrabarBTNActionPerformed
        guardarCompraEnBaseDeDatos();
    }//GEN-LAST:event_GrabarBTNActionPerformed

    private int codigoTipoComprobante(boolean sw, String cad) {
        int codigo = 1001;
        Vector<TipoComprobante> listaTipComp;
        listaTipComp = tipCompDAO.listaTipoComprobante(sw, cad);
        for (int i = 0; i < listaTipComp.size(); i++) {
            codigo = listaTipComp.get(i).getIdTipComp();
        }
        return codigo;
    }

    private void BtnBuscarProveedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnBuscarProveedorActionPerformed
        Proveedor p;
        SelProveedor dialog = new SelProveedor(new javax.swing.JFrame(), true);
        dialog.setVisible(true);
        p = dialog.devProv();
        this.txtIdProveedor.setText(String.valueOf(p.getIdProveedor()));
        this.txtNifProveedor.setText(p.getNif());
        this.txtProveedor.setText(p.getNombre());

    }//GEN-LAST:event_BtnBuscarProveedorActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnAgregar;
    private javax.swing.JButton BtnBuscarProveedor;
    private javax.swing.JComboBox<String> CmbTipoComp;
    private javax.swing.JButton GrabarBTN;
    private javax.swing.JPanel JPFormCompra;
    private javax.swing.JButton LimpiarBTN;
    private javax.swing.JTable TBLdetCompra;
    private javax.swing.JButton Totalizar;
    private javax.swing.JButton btnBuscarProd;
    private com.toedter.calendar.JDateChooser calFecha;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField txtCantProd;
    private javax.swing.JTextField txtCatProd;
    private javax.swing.JTextField txtCorrelativo;
    private javax.swing.JTextField txtDescuentoProd;
    private javax.swing.JTextField txtIGV;
    private javax.swing.JTextField txtIdProd;
    private javax.swing.JTextField txtIdProveedor;
    private javax.swing.JTextField txtImporte;
    private javax.swing.JTextField txtNifProveedor;
    private javax.swing.JTextField txtNombProd;
    private javax.swing.JTextField txtPrecioProd;
    private javax.swing.JTextField txtProveedor;
    private javax.swing.JTextField txtSerie;
    private javax.swing.JTextField txtSubTotal;
    private javax.swing.JTextField txtTotal;
    // End of variables declaration//GEN-END:variables
}
