/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package UI.internal;

import DAO.Impl.UtilComprasDAOImpl;
import DAO.Impl.UtilVentasDAOImpl;
import DAO.UtilComprasDAO;
import DAO.UtilVentasDAO;
import UTIL.EmailOnlyDocument;
import UTIL.NumberOnlyDocument;
import UTIL.TextOnlyDocument;
import UTIL.UtilEmailSender;
import java.util.ArrayList;
import java.util.List;
import java.util.StringJoiner;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.mail.MessagingException;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JTextField;
import net.sf.jasperreports.engine.JRException;

/**
 *
 * @author xhesm
 */
public class InFrmCorreo extends javax.swing.JInternalFrame {

    /**
     * Creates new form InFrmCorreo
     */
    public InFrmCorreo() {
        initComponents();
        this.setClosable(true);
        default_validaciones();
    }

    public void default_validaciones() {
        txtAsunto.setDocument(new TextOnlyDocument(100));
        txtCorreo.setDocument(new EmailOnlyDocument(60));
        txtAContenido.setDocument(new TextOnlyDocument(200));
        rbNinguno.setSelected(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        txtAsunto = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtAContenido = new javax.swing.JTextArea();
        jLabel3 = new javax.swing.JLabel();
        txtCorreo = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        rbReporteVenta = new javax.swing.JRadioButton();
        rbCompras = new javax.swing.JRadioButton();
        rbNinguno = new javax.swing.JRadioButton();
        jButton2 = new javax.swing.JButton();
        lblmssg = new javax.swing.JLabel();

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Envio de Correo"));

        txtAsunto.setName("Asunto"); // NOI18N

        jLabel1.setText("Asunto :");

        jLabel2.setText("Contenido :");

        txtAContenido.setColumns(20);
        txtAContenido.setRows(5);
        jScrollPane1.setViewportView(txtAContenido);

        jLabel3.setText("Correo :");

        txtCorreo.setName("Correo"); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtAsunto)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 366, Short.MAX_VALUE)
                    .addComponent(txtCorreo)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtAsunto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Incluir Reportes"));

        rbReporteVenta.setText("Reporte de Ventas X Trabajador");

        rbCompras.setText("Listado de Compras");
        rbCompras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbComprasActionPerformed(evt);
            }
        });

        rbNinguno.setText("Ninguno");
        rbNinguno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbNingunoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rbReporteVenta)
                    .addComponent(rbCompras)
                    .addComponent(rbNinguno))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(rbNinguno)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rbReporteVenta)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rbCompras)
                .addContainerGap(8, Short.MAX_VALUE))
        );

        jButton2.setText("Enviar Correo");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblmssg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton2)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(lblmssg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void rbComprasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbComprasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbComprasActionPerformed

    private void rbNingunoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbNingunoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbNingunoActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        try {
            // TODO add your handling code here:
            UtilEmailSender emailSender = new UtilEmailSender();
            UtilComprasDAO comprasDAO = new UtilComprasDAOImpl();
            UtilVentasDAO ventasDAO = new UtilVentasDAOImpl();
            List<String> paths = new ArrayList<>();

            if (!llenarError(txtAsunto, txtCorreo)) {
                if (rbReporteVenta.isSelected()) {
                    ventasDAO.guardarReporte();
                    paths.add("config/temporal-reports/VentasXTrabajador.pdf");
                } else if (rbCompras.isSelected()) {
                    comprasDAO.guardarReporte();
                    paths.add("config/temporal-reports/ReporteCompras.pdf");
                }
                emailSender.setAsunto(txtAsunto.getText());
                emailSender.setContenido(txtAContenido.getText());
                emailSender.setCorreo_receptor(txtCorreo.getText());
                emailSender.setPaths(paths);
                if (emailSender.enviarInformePorCorreo()) {
                    lblmssg.setText("CORREO ENVIADO CORRECTAMENTE");
                } else {
                    lblmssg.setText("ERROR EN EL PROCESO DE ENVÍO");
                }
            }
        } catch (MessagingException ex) {
            lblmssg.setText(ex.getLocalizedMessage());
            //Logger.getLogger(InFrmCorreo.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_jButton2ActionPerformed

    public boolean llenarError(JTextField... jTxtFields) {
        JPanel panel = new JPanel();
        StringJoiner joiner = new StringJoiner("<br>");
        for (JTextField jtxtfield : jTxtFields) {
            System.out.println("field" + jtxtfield.getName());
            if (jtxtfield.getText().isEmpty()) {
                joiner.add(jtxtfield.getName().concat(" no puede estar vacío"));
            }
        }
        if (!joiner.toString().isEmpty()) {
            panel.add(new JLabel("<html><font color='red'>" + joiner.toString() + "</font></html>"));
            JOptionPane.showOptionDialog(
                    null,
                    panel,
                    "Alerta",
                    JOptionPane.WARNING_MESSAGE,
                    JOptionPane.WARNING_MESSAGE,
                    null,
                    new Object[]{},
                    null
            );
        }
        return !joiner.toString().isEmpty();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblmssg;
    private javax.swing.JRadioButton rbCompras;
    private javax.swing.JRadioButton rbNinguno;
    private javax.swing.JRadioButton rbReporteVenta;
    private javax.swing.JTextArea txtAContenido;
    private javax.swing.JTextField txtAsunto;
    private javax.swing.JTextField txtCorreo;
    // End of variables declaration//GEN-END:variables
}
