/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package UI.internal;

import BEAN.CabVenta;
import BEAN.DetVenta;
import DAO.Conexion;
import DAO.Impl.UtilClienteDAOImpl;
import DAO.Impl.UtilProductoDAOImpl;
import DAO.Impl.UtilVentasDAOImpl;
import DAO.UtilClienteDAO;
import DAO.UtilProductoDAO;
import DAO.UtilVentasDAO;
import UI.FrmPrincipal;
import UTIL.NumberOnlyDocument;
import UTIL.NumberOnlyDocumentSize;
import java.io.FileOutputStream;
import java.io.IOException;
import java.text.DecimalFormat;
import java.text.DecimalFormatSymbols;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.Properties;
import java.util.StringJoiner;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author xhesm
 */
public class InFrmVenta extends javax.swing.JInternalFrame {

    /**
     * Creates new form InFrmVenta
     */
    UtilProductoDAO utilProductoDAO = new UtilProductoDAOImpl();
    DefaultTableModel model = new DefaultTableModel();
    DecimalFormatSymbols simbolos = new DecimalFormatSymbols();

//    
    DecimalFormat decimalFormat = new DecimalFormat("#0.00");
    UtilClienteDAO clienteDAO = new UtilClienteDAOImpl();
    UtilVentasDAO utilVentasDAO = new UtilVentasDAOImpl();

    public int ID_CLIENTE = 0;

    public InFrmVenta() {
        initComponents();
        this.setClosable(true);
        this.setResizable(true);
        this.setTitle("VENTAS");
        default_Init();
        textfields_config();
        simbolos.setDecimalSeparator('.');
        decimalFormat = new DecimalFormat("#0.00", simbolos);
    }

    private void default_Init() {

        this.jtblProd.setModel(this.utilProductoDAO.llenartabla());
        model.addColumn("Id");
        model.addColumn("Descripcion");
        model.addColumn("Precio U");
        model.addColumn("Cantidad");
        model.addColumn("Descuento");
        model.addColumn("SubTotal");
        this.jbtlDet.setModel(model);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        menuOpciones = new javax.swing.JPopupMenu();
        mnActualizar = new javax.swing.JMenuItem();
        mnEliminar = new javax.swing.JMenuItem();
        jPanel1 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        txtPrdID = new javax.swing.JTextField();
        txtPrdDesc = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        txtPrdPrU = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        txtCant = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        txtsubT = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        txtDesc = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        btnAgregar = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jbtlDet = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        txtdniRuc = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        txtCliDoc = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtCliDatos = new javax.swing.JTextField();
        jPanel6 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtSerie = new javax.swing.JTextField();
        txtNro = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        cboTipoDoc = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        txtBuscarProd = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        jtblProd = new javax.swing.JTable();
        lblTotal = new javax.swing.JLabel();
        lblImpuesto = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();

        mnActualizar.setText("Actualizar");
        mnActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnActualizarActionPerformed(evt);
            }
        });
        menuOpciones.add(mnActualizar);

        mnEliminar.setBackground(new java.awt.Color(255, 0, 0));
        mnEliminar.setText("Eliminar");
        mnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnEliminarActionPerformed(evt);
            }
        });
        menuOpciones.add(mnEliminar);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Detalle Producto"));

        jLabel13.setText("Precio Unitario :");

        txtPrdID.setEnabled(false);
        txtPrdID.setName("Producto Seleccionado"); // NOI18N

        txtPrdDesc.setEnabled(false);

        jLabel12.setText("Descripción :");

        txtPrdPrU.setEnabled(false);

        jLabel11.setText("ID :");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addGap(138, 138, 138))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                        .addComponent(txtPrdID, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(22, 22, 22)))
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtPrdDesc, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12))
                .addGap(18, 18, 18)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtPrdPrU, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11)
                            .addComponent(jLabel12))
                        .addGap(2, 2, 2)
                        .addComponent(txtPrdID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(txtPrdDesc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(jLabel13)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtPrdPrU, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        jLabel14.setText("Cantidad :");

        txtCant.setName("Campo Cantidad"); // NOI18N
        txtCant.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCantActionPerformed(evt);
            }
        });
        txtCant.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtCantKeyReleased(evt);
            }
        });

        jLabel15.setText("SubTotal :");

        txtsubT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtsubTActionPerformed(evt);
            }
        });

        jLabel16.setText("Descuento :");

        txtDesc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDescActionPerformed(evt);
            }
        });
        txtDesc.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtDescKeyReleased(evt);
            }
        });

        jLabel17.setText("%");

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addComponent(txtCant, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addComponent(txtsubT, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addComponent(txtDesc, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addComponent(jLabel17)
                .addContainerGap())
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(txtCant, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(txtsubT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(txtDesc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        btnAgregar.setText(" ↓↓↓↓ Agregar ↓↓↓↓");
        btnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel7, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel8, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnAgregar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnAgregar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Productos"));
        jPanel2.setLayout(new javax.swing.BoxLayout(jPanel2, javax.swing.BoxLayout.LINE_AXIS));

        jbtlDet.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null}
            },
            new String [] {
                "Id", "Descripcion", "Precio U", "Cantidad", "SubTotal"
            }
        ));
        jbtlDet.setComponentPopupMenu(menuOpciones);
        jbtlDet.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbtlDet.setGridColor(new java.awt.Color(102, 204, 0));
        jbtlDet.setSelectionBackground(new java.awt.Color(102, 204, 0));
        jScrollPane1.setViewportView(jbtlDet);

        jPanel2.add(jScrollPane1);

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Venta"));

        jLabel1.setText("DNI O RUC :");

        jButton2.setText("Buscar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder("Detalle Cliente"));

        txtCliDoc.setEnabled(false);
        txtCliDoc.setName("Documento Cliente"); // NOI18N

        jLabel2.setText("Documento");

        jLabel3.setText("Datos");

        txtCliDatos.setEnabled(false);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtCliDoc, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtCliDatos)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel3)
                        .addComponent(txtCliDatos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel2)
                        .addComponent(txtCliDoc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jLabel5.setText("-");

        jLabel4.setText("Serie-Numero");

        txtSerie.setName("Serie Documento"); // NOI18N

        txtNro.setName("Nro Documento"); // NOI18N

        jLabel6.setText("Tipo Documento");

        cboTipoDoc.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "BOLETA" }));

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cboTipoDoc, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtSerie, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 5, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtNro, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cboTipoDoc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(jLabel4)
                    .addComponent(txtSerie, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtdniRuc)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton2))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtdniRuc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(jButton2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jButton1.setBackground(new java.awt.Color(51, 255, 0));
        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton1.setText("Generar Venta");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder("Productos"));

        txtBuscarProd.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtBuscarProdKeyReleased(evt);
            }
        });

        jtblProd.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "ID", "Detalle"
            }
        ));
        jtblProd.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jtblProd.setGridColor(new java.awt.Color(102, 204, 0));
        jtblProd.setSelectionBackground(new java.awt.Color(102, 204, 0));
        jtblProd.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtblProdMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jtblProd);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(txtBuscarProd, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addComponent(txtBuscarProd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2))
        );

        lblTotal.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblTotal.setText("0.00");

        lblImpuesto.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblImpuesto.setText("0.00");

        jLabel9.setText("Impuesto :");

        jLabel10.setText("Total : ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblImpuesto)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblTotal)
                        .addGap(46, 46, 46)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblTotal)
                            .addComponent(lblImpuesto)
                            .addComponent(jLabel9)
                            .addComponent(jLabel10)))
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:

        boolean condicionerror = llenarError(txtCliDoc, txtSerie, txtNro);
        if (!condicionerror) {
            int filas = model.getRowCount();
            if (filas == 0) {
                JPanel panel = new JPanel();
                panel.add(new JLabel("<html><font color='red'>Deben haber productos en el documento</font></html>"));
                JOptionPane.showOptionDialog(
                        null,
                        panel,
                        "Alerta",
                        JOptionPane.WARNING_MESSAGE,
                        JOptionPane.WARNING_MESSAGE,
                        null,
                        new Object[]{},
                        null
                );
            } else {
                if (utilVentasDAO.buscarSerieAndNumeroReply(txtSerie.getText().trim(), txtNro.getText().trim())) {
                    JOptionPane.showMessageDialog(this, "EL NRO DE SERIE Y CORRELATIVO YA EXISTEN , VUELVA A INTENTARLO CON OTROS");
                } else {
                    CabVenta cabVenta = new CabVenta();
                    List<DetVenta> detventals = new ArrayList<>();
                    cabVenta.setCorrelativo(txtNro.getText());
                    cabVenta.setSerie(txtSerie.getText());
                    cabVenta.setTotal(Double.parseDouble(lblTotal.getText()));
                    cabVenta.setImpuesto(Double.parseDouble(lblImpuesto.getText()));
                    cabVenta.setIdUsuarioReg(FrmPrincipal.ID_USUARIO_SESION);
                    cabVenta.setIdCliente(ID_CLIENTE);
                    int idTipODoc = cboTipoDoc.getSelectedIndex() + 1;
                    cabVenta.setIdTipComp(idTipODoc);

                    int rowCount = jbtlDet.getRowCount();

                    for (int i = 0; i < rowCount; i++) {
                        //   sum += Double.parseDouble(jbtlDet.getValueAt(i, columnIndex) + "");
                        DetVenta detVenta = new DetVenta();
                        detVenta.setIdProducto(Integer.parseInt(jbtlDet.getValueAt(i, 0) + ""));
                        detVenta.setCantidad(Integer.parseInt(jbtlDet.getValueAt(i, 3) + ""));
                        detVenta.setDescuento(Integer.parseInt(jbtlDet.getValueAt(i, 4) + ""));
                        detVenta.setImporte(Double.parseDouble(jbtlDet.getValueAt(i, 5) + ""));
                        detventals.add(detVenta);
                    }

                    boolean registrado = utilVentasDAO.guardarVenta(cabVenta, detventals);
                    if (registrado) {

                        int opcion = JOptionPane.showConfirmDialog(this, "Venta Registrada, ¿Desea Imprimir?");
                        if (opcion == JOptionPane.YES_OPTION) {
                            Map<String, Object> map = new HashMap<>();
                            map.put("id_venta", cabVenta.getIdVenta());
                            map.put("SerieNro", "B" + cabVenta.getSerie() + "-" + cabVenta.getCorrelativo());
                            map.put("Nombres", txtCliDatos.getText());
                            map.put("dni", txtCliDoc.getText());
                            map.put("impuesto", lblImpuesto.getText());
                            map.put("total", lblTotal.getText());
                            utilVentasDAO.mostrarCpe(map);
                            // El usuario seleccionó "Sí" 
                            //System.out.println("Usuario seleccionó Sí");
                            // Aquí puedes poner el código que quieres ejecutar cuando el usuario selecciona "Sí"
                        } else {
                            // El usuario seleccionó "No" o cerró el cuadro de diálogo
                            System.out.println("Usuario seleccionó No o cerró el cuadro de diálogo");
                            // Aquí puedes poner el código que quieres ejecutar cuando el usuario selecciona "No" o cierra el cuadro de diálogo
                        }

                    }
                }
            }
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    public boolean llenarError(JTextField... jTxtFields) {
        JPanel panel = new JPanel();
        StringJoiner joiner = new StringJoiner("<br>");
        for (JTextField jtxtfield : jTxtFields) {
            System.out.println("field" + jtxtfield.getName());
            if (jtxtfield.getText().isEmpty()) {
                joiner.add(jtxtfield.getName().concat(" no puede estar vacío"));
            }
        }
        if (!joiner.toString().isEmpty()) {
            panel.add(new JLabel("<html><font color='red'>" + joiner.toString() + "</font></html>"));
            JOptionPane.showOptionDialog(
                    null,
                    panel,
                    "Alerta",
                    JOptionPane.WARNING_MESSAGE,
                    JOptionPane.WARNING_MESSAGE,
                    null,
                    new Object[]{},
                    null
            );
        }
        return !joiner.toString().isEmpty();
    }

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:

        Object[][] cli = clienteDAO.buscarClienteByNdif(txtdniRuc.getText().trim());
        ID_CLIENTE = Integer.parseInt(cli[0][0] + "");
        txtCliDoc.setText(cli[0][1] + "");
        txtCliDatos.setText(cli[0][2] + "");
    }//GEN-LAST:event_jButton2ActionPerformed

    private void txtCantActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCantActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCantActionPerformed

    private void txtsubTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtsubTActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtsubTActionPerformed

    private void txtDescActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDescActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDescActionPerformed
    int selectRow = -1;
    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarActionPerformed
        // TODO add your handling code here:
//txtCant.getText().isEmpty() || txtPrdID.getText().isEmpty()
        if (!llenarError(txtCant, txtPrdID)) {
            System.out.println("selectRow1 " + selectRow);
            if (selectRow != -1 && btnAgregar.getText().equals("↓↓↓↓ Actualizar ↓↓↓↓")) {
                btnAgregar.setText(" ↓↓↓↓ Agregar ↓↓↓↓");
                System.out.println("selectRow" + selectRow);

                model.setValueAt(txtPrdID.getText(), selectRow, 0);
                model.setValueAt(txtPrdDesc.getText(), selectRow, 1);
                model.setValueAt(txtPrdPrU.getText(), selectRow, 2);
                model.setValueAt(txtCant.getText(), selectRow, 3);
                model.setValueAt(txtDesc.getText().trim().isEmpty() ? "0" : txtDesc.getText().trim(), selectRow, 4);
                model.setValueAt(txtsubT.getText(), selectRow, 5);

            } else {//if (btnAgregar.getText().equals(" ↓↓↓↓ Agregar ↓↓↓↓")) {
                btnAgregar.setText(" ↓↓↓↓ Agregar ↓↓↓↓");
                System.out.println("guardandno");
                Object[] newRow = {txtPrdID.getText(), txtPrdDesc.getText(), txtPrdPrU.getText(), txtCant.getText(), txtDesc.getText().trim().isEmpty() ? "0" : txtDesc.getText().trim(), txtsubT.getText()};
                model.addRow(newRow);
            }
            txtDesc.setText("");
            txtCant.setText("");
            txtsubT.setText("");
            calcularImpuestoYTotal();
        }
    }//GEN-LAST:event_btnAgregarActionPerformed

    private void mnActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnActualizarActionPerformed
        // TODO add your handling code here:
        int selectedRow = jbtlDet.getSelectedRow();
        this.selectRow = selectedRow;
        if (selectedRow != -1) {
            int id = Integer.parseInt(jbtlDet.getValueAt(selectedRow, 0) + "");
            String desc = jbtlDet.getValueAt(selectedRow, 1) + "";
            double precioU = Double.parseDouble(jbtlDet.getValueAt(selectedRow, 2) + "");
            int cantidad = Integer.parseInt(jbtlDet.getValueAt(selectedRow, 3) + "");
            int descuento = Integer.parseInt(jbtlDet.getValueAt(selectedRow, 4) + "");
            double subtotal = Double.parseDouble(jbtlDet.getValueAt(selectedRow, 5) + "");

            txtPrdID.setText(id + "");
            txtPrdDesc.setText(desc + "");
            txtPrdPrU.setText(precioU + "");

            txtCant.setText(cantidad + "");
            txtDesc.setText(descuento + "");
            txtsubT.setText(subtotal + "");
            btnAgregar.setText("↓↓↓↓ Actualizar ↓↓↓↓");
            // Actualizar valores en la fila seleccionada
            //model.setValueAt("Dato Actualizado 1", selectedRow, 0);
            //model.setValueAt("Dato Actualizado 2", selectedRow, 1);
        }
        calcularImpuestoYTotal();
    }//GEN-LAST:event_mnActualizarActionPerformed

    private void txtBuscarProdKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBuscarProdKeyReleased
        // TODO add your handling code here:
        jtblProd.setModel(this.utilProductoDAO.buscarEnTabla(txtBuscarProd.getText()));
    }//GEN-LAST:event_txtBuscarProdKeyReleased

    private void jtblProdMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtblProdMouseClicked
        // TODO add your handling code here:
        int selectedRow = jtblProd.getSelectedRow();
        if (selectedRow != -1) {
            // Obtener datos de la fila seleccionada
            int idProducto = Integer.parseInt((String) jtblProd.getValueAt(selectedRow, 0));
            Object[][] dataPrd = utilProductoDAO.buscarProductoById(idProducto);
            txtPrdID.setText(dataPrd[0][0] + "");
            txtPrdDesc.setText(dataPrd[0][1] + "");
            txtPrdPrU.setText(dataPrd[0][2] + "");

        }
    }//GEN-LAST:event_jtblProdMouseClicked

    private void txtCantKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCantKeyReleased
        // TODO add your handling code here:
        // TODO add your handling code here:
        double prU = Double.parseDouble(txtPrdPrU.getText());
        int cantidad = Integer.parseInt(txtCant.getText().isEmpty() ? "0" : txtCant.getText());
        double descuento = Double.parseDouble(txtDesc.getText().isEmpty() ? "0" : txtDesc.getText());
        System.out.println(descuento);
        System.out.println("" + (100 - descuento) / 100);
        double descDo = (100 - descuento) / 100;
        System.out.println("descDo1 " + descDo);
        descDo = descDo == 0 ? 1.0f : descDo;
        System.out.println("descDo2 " + descDo);
        double PrXU = (prU * cantidad);
        txtsubT.setText(decimalFormat.format(PrXU * descDo));
    }//GEN-LAST:event_txtCantKeyReleased

    private void txtDescKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtDescKeyReleased
        // TODO add your handling code here:
        double prU = Double.parseDouble(txtPrdPrU.getText());
        int cantidad = Integer.parseInt(txtCant.getText().isEmpty() ? "0" : txtCant.getText());
        double descuento = Double.parseDouble(txtDesc.getText().isEmpty() ? "0" : txtDesc.getText());
        System.out.println(descuento);
        System.out.println("" + (100 - descuento) / 100);
        double descDo = (100 - descuento) / 100;
        System.out.println("descDo1 " + descDo);
        descDo = descDo == 0 ? 1.0f : descDo;
        System.out.println("descDo2 " + descDo);
        double PrXU = (prU * cantidad);
        txtsubT.setText(decimalFormat.format(PrXU * descDo));
    }//GEN-LAST:event_txtDescKeyReleased

    private void mnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnEliminarActionPerformed
        // TODO add your handling code here:

        int selectedRow = jbtlDet.getSelectedRow();
        if (selectedRow != -1) {
            // Quitar la fila seleccionada
            model.removeRow(selectedRow);
        }
        calcularImpuestoYTotal();
    }//GEN-LAST:event_mnEliminarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregar;
    private javax.swing.JComboBox<String> cboTipoDoc;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jbtlDet;
    private javax.swing.JTable jtblProd;
    private javax.swing.JLabel lblImpuesto;
    private javax.swing.JLabel lblTotal;
    private javax.swing.JPopupMenu menuOpciones;
    private javax.swing.JMenuItem mnActualizar;
    private javax.swing.JMenuItem mnEliminar;
    private javax.swing.JTextField txtBuscarProd;
    private javax.swing.JTextField txtCant;
    private javax.swing.JTextField txtCliDatos;
    private javax.swing.JTextField txtCliDoc;
    private javax.swing.JTextField txtDesc;
    private javax.swing.JTextField txtNro;
    private javax.swing.JTextField txtPrdDesc;
    private javax.swing.JTextField txtPrdID;
    private javax.swing.JTextField txtPrdPrU;
    private javax.swing.JTextField txtSerie;
    private javax.swing.JTextField txtdniRuc;
    private javax.swing.JTextField txtsubT;
    // End of variables declaration//GEN-END:variables

    private void textfields_config() {
        txtCant.setDocument(new NumberOnlyDocument(3));
        txtDesc.setDocument(new NumberOnlyDocumentSize(100));
        txtSerie.setDocument(new NumberOnlyDocument(3));
        txtNro.setDocument(new NumberOnlyDocument(4));
    }

    private void calcularImpuestoYTotal() {

        int columnIndex = 5; // Índice de la columna a sumar
        int rowCount = jbtlDet.getRowCount();
        double sum = 0;

        for (int i = 0; i < rowCount; i++) {
            sum += Double.parseDouble(jbtlDet.getValueAt(i, columnIndex) + "");
        }
        lblTotal.setText(decimalFormat.format(sum) + "");
        lblImpuesto.setText(decimalFormat.format(sum * 0.18));

    }

}
