/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package UI.internal;

import BEAN.Cliente;
import BEAN.ComboData;
import BEAN.Trabajador;
import DAO.ClienteDAO;
import DAO.Impl.ClienteDAOImpl;
import DAO.Impl.UbigeoUtilDAOImpl;
import DAO.UbigeoUtilDAO;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import java.util.Enumeration;
import java.util.StringJoiner;
import javax.swing.AbstractButton;
import javax.swing.ButtonGroup;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author xhesm
 */
public class InFrmCliente extends javax.swing.JInternalFrame {

    /**
     * Creates new form InFrmCliente
     */
    UbigeoUtilDAO ubigeoDAO = new UbigeoUtilDAOImpl();
    ClienteDAO clienteDAO = new ClienteDAOImpl();

    DefaultTableModel defaultTableModel = new DefaultTableModel();
    Object[][] select, selectaux;
    DefaultComboBoxModel<ComboData> boxModel = null;
    DefaultComboBoxModel<String> boxDep, boxProv, boxDisc = null;

    public InFrmCliente() {
        this.setClosable(true);
        this.setResizable(true);
        this.setTitle("Cliente");
        initComponents();
        config_ubigeo();
        tablas();
    }

    public void config_ubigeo() {
        boxDep = ubigeoDAO.llenarcomboDep();
        cboDepa.setModel(boxDep);
        cboDepa.setSelectedIndex(2);
        txtUbigeo.setText(ubigeoDAO.getUbigeoByDeptProvDist(cboDepa.getSelectedItem().toString(), cboProv.getSelectedItem().toString(), cboDistrito.getSelectedItem().toString()));
    }

    public void tablas() {
        tblCliente.setModel(clienteDAO.llenartabla());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnGrpEstado = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        txtnroDocumento = new javax.swing.JTextField();
        txtid = new javax.swing.JTextField();
        txtnombre = new javax.swing.JTextField();
        txtUbigeo = new javax.swing.JTextField();
        txtdireccion = new javax.swing.JTextField();
        rbActivo = new javax.swing.JRadioButton();
        rbInactivo = new javax.swing.JRadioButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtCelular = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        txtTelefono = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        txtCorreo = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        btnNuevo = new javax.swing.JButton();
        btnregistro = new javax.swing.JButton();
        cboDepa = new javax.swing.JComboBox<>();
        jLabel14 = new javax.swing.JLabel();
        cboProv = new javax.swing.JComboBox<>();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        cboDistrito = new javax.swing.JComboBox<>();
        jLabel17 = new javax.swing.JLabel();
        btnEliminar = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblCliente = new javax.swing.JTable();
        txtBuscador = new javax.swing.JTextField();
        cboBuscar = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();

        getContentPane().setLayout(new javax.swing.BoxLayout(getContentPane(), javax.swing.BoxLayout.PAGE_AXIS));

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Cliente"));

        txtnroDocumento.setName("Nro Documento"); // NOI18N

        txtid.setEnabled(false);

        txtnombre.setName("Nombre"); // NOI18N

        txtUbigeo.setEnabled(false);
        txtUbigeo.setName("Ubigeo"); // NOI18N

        txtdireccion.setName("Dirección"); // NOI18N

        rbActivo.setText("Activo");
        rbActivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbActivoActionPerformed(evt);
            }
        });

        rbInactivo.setText("Inactivo");
        rbInactivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbInactivoActionPerformed(evt);
            }
        });

        jLabel1.setText("Id");

        jLabel3.setText("Nombre");

        jLabel4.setText("Nro Documento");

        jLabel7.setText("Ubigeo");

        jLabel9.setText("Dirección");

        txtCelular.setName("Celular"); // NOI18N

        jLabel11.setText("Celular");

        txtTelefono.setName("Teléfono"); // NOI18N

        jLabel12.setText("Teléfono");

        txtCorreo.setName("Correo"); // NOI18N

        jLabel13.setText("Correo");

        btnNuevo.setText("Nuevo");
        btnNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevoActionPerformed(evt);
            }
        });

        btnregistro.setText("Registrar");
        btnregistro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnregistroActionPerformed(evt);
            }
        });

        cboDepa.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cboDepaItemStateChanged(evt);
            }
        });
        cboDepa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboDepaActionPerformed(evt);
            }
        });

        jLabel14.setText("Departamento");

        cboProv.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cboProvItemStateChanged(evt);
            }
        });

        jLabel15.setText("Provincia");

        jLabel16.setText("Distrito");

        cboDistrito.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cboDistritoItemStateChanged(evt);
            }
        });

        jLabel17.setText("Estado");

        btnEliminar.setText("Eliminar");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });

        jButton2.setText("Ver Reporte");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnNuevo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnregistro)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnEliminar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton2))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel12)
                            .addComponent(txtTelefono, javax.swing.GroupLayout.DEFAULT_SIZE, 192, Short.MAX_VALUE)
                            .addComponent(jLabel1)
                            .addComponent(txtnroDocumento)
                            .addComponent(jLabel4)
                            .addComponent(txtnombre)
                            .addComponent(jLabel3)
                            .addComponent(txtid)
                            .addComponent(jLabel9)
                            .addComponent(txtdireccion)
                            .addComponent(jLabel13)
                            .addComponent(txtCorreo))
                        .addGap(102, 102, 102)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(rbActivo)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(rbInactivo))
                            .addComponent(jLabel17)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel14)
                                .addComponent(jLabel16)
                                .addComponent(jLabel15)
                                .addComponent(cboDistrito, 0, 194, Short.MAX_VALUE)
                                .addComponent(cboProv, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(cboDepa, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(jLabel11)
                            .addComponent(txtCelular, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7)
                            .addComponent(txtUbigeo, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 4, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel14)
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cboDepa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel15)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cboProv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(2, 2, 2)
                                .addComponent(txtnroDocumento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel16)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(cboDistrito, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(1, 1, 1)
                        .addComponent(txtnombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addGap(5, 5, 5)
                        .addComponent(txtUbigeo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel9)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(txtdireccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(jLabel12))
                .addGap(1, 1, 1)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCelular, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel13)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel17)
                        .addGap(3, 3, 3)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(rbActivo)
                            .addComponent(rbInactivo))))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnNuevo)
                    .addComponent(btnregistro)
                    .addComponent(btnEliminar)
                    .addComponent(jButton2))
                .addContainerGap())
        );

        getContentPane().add(jPanel1);

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        tblCliente.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        tblCliente.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblCliente.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        tblCliente.setGridColor(new java.awt.Color(102, 204, 0));
        tblCliente.setRowHeight(15);
        tblCliente.setRowMargin(1);
        tblCliente.setSelectionBackground(new java.awt.Color(102, 204, 0));
        tblCliente.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_INTERVAL_SELECTION);
        tblCliente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblClienteMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblCliente);

        cboBuscar.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "TODOS", "DNI", "NOMBRE", "TELEFONO", "CELULAR" }));
        cboBuscar.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cboBuscarItemStateChanged(evt);
            }
        });

        jButton1.setText("Buscar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 516, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(cboBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtBuscador)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton1)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtBuscador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cboBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 283, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel2);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void rbActivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbActivoActionPerformed
        // TODO add your handling code here:
        String selectedValue = getSelectedButtonValue(btnGrpEstado);
        System.out.println(selectedValue);
    }//GEN-LAST:event_rbActivoActionPerformed

    private void rbInactivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbInactivoActionPerformed
        // TODO add your handling code here:
        String selectedValue = getSelectedButtonValue(btnGrpEstado);
        System.out.println(selectedValue);
    }//GEN-LAST:event_rbInactivoActionPerformed

    private static String getSelectedButtonValue(ButtonGroup buttonGroup) {
        for (Enumeration<AbstractButton> buttons = buttonGroup.getElements(); buttons.hasMoreElements();) {
            AbstractButton button = buttons.nextElement();
            if (button.isSelected()) {
                return button.getText();
            }
        }
        return null;
    }

    private void btnNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevoActionPerformed
        limpiar();
    }//GEN-LAST:event_btnNuevoActionPerformed

    void setDataCliente(Cliente c) {
        txtCelular.setText(c.getCelular());
        txtCorreo.setText(c.getCorreo());
        txtTelefono.setText(c.getTelefono());
        txtUbigeo.setText(c.getIdUbigeo());
        txtdireccion.setText(c.getDireccion());
        txtid.setText(c.getIdCliente() + "");
        txtnombre.setText(c.getNombre());
        txtnroDocumento.setText(c.getNif());
        rbActivo.setSelected(c.getEstado() == 1);
        rbInactivo.setSelected(c.getEstado() == 0);
        btnregistro.setText("Actualizar");
    }

    void limpiar() {
        txtBuscador.setText("");
        txtCelular.setText("");
        txtCorreo.setText("");
        txtTelefono.setText("");
        txtUbigeo.setText("");
        txtdireccion.setText("");
        txtid.setText("");
        txtnombre.setText("");
        txtnroDocumento.setText("");
        btnregistro.setText("Registrar");
    }
    private void btnregistroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnregistroActionPerformed
        // TODO add your handling code here:

        Cliente t = new Cliente();
        t.setDireccion(txtdireccion.getText());
        t.setNombre(txtnombre.getText());
        t.setCelular(txtCelular.getText());
        t.setCorreo(txtCorreo.getText());
        t.setIdUbigeo(txtUbigeo.getText());
        t.setNif(txtnroDocumento.getText());
        t.setTelefono(txtTelefono.getText());
        t.setEstado((short) (rbActivo.isSelected() ? 1 : 0));
        boolean condicionerror
                = llenarError(
                        txtdireccion,
                        txtnombre,
                        txtCelular,
                        txtCorreo,
                        txtUbigeo,
                        txtnroDocumento,
                        txtTelefono);

        System.out.println(this.btnregistro.getText());
        if (!condicionerror) {
            switch (this.btnregistro.getText()) {
                case "Registrar":
                    t.setIdCliente(0);
                    if (clienteDAO.save(t)) {
                        JOptionPane.showMessageDialog(this, "Cliente Guardado Correctamente", "Mensaje de confirmación", JOptionPane.INFORMATION_MESSAGE);
                        tblCliente.setModel(clienteDAO.llenartabla());
                    }
                    break;
                case "Actualizar":
                    t.setIdCliente(Integer.parseInt(txtid.getText()));
                    if (clienteDAO.save(t)) {
                        JOptionPane.showMessageDialog(this, "Cliente Actualizado Correctamete", "Mensaje de confirmación", JOptionPane.INFORMATION_MESSAGE);
                        tblCliente.setModel(clienteDAO.llenartabla());
                    }
                    break;
            }
        }
    }//GEN-LAST:event_btnregistroActionPerformed

    public boolean llenarError(JTextField... jTxtFields) {
        JPanel panel = new JPanel();
        StringJoiner joiner = new StringJoiner("<br>");
        for (JTextField jtxtfield : jTxtFields) {
            System.out.println("field" + jtxtfield.getName());
            if (jtxtfield.getText().isEmpty()) {
                joiner.add(jtxtfield.getName().concat(" no puede estar vacío"));
            }
        }
        if (!joiner.toString().isEmpty()) {
            panel.add(new JLabel("<html><font color='red'>" + joiner.toString() + "</font></html>"));
            JOptionPane.showOptionDialog(
                    null,
                    panel,
                    "Alerta",
                    JOptionPane.WARNING_MESSAGE,
                    JOptionPane.WARNING_MESSAGE,
                    null,
                    new Object[]{},
                    null
            );
        }
        return !joiner.toString().isEmpty();
    }
    private void cboDepaItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cboDepaItemStateChanged
        // TODO add your handling code here:

        boxProv = ubigeoDAO.llenarcomboProv((String) boxDep.getSelectedItem());
        cboProv.setModel(boxProv);
        boxDisc = ubigeoDAO.llenarcomboDist((String) boxProv.getSelectedItem());
        cboDistrito.setModel(boxDisc);
        txtUbigeo.setText(ubigeoDAO.getUbigeoByDeptProvDist(cboDepa.getSelectedItem().toString(), cboProv.getSelectedItem().toString(), cboDistrito.getSelectedItem().toString()));
        // boxProv = ubigeoDAO.llenarcomboProv(((ComboData) boxDep.getSelectedItem()).getText());
    }//GEN-LAST:event_cboDepaItemStateChanged

    private void cboDepaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboDepaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cboDepaActionPerformed

    private void cboProvItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cboProvItemStateChanged
        // TODO add your handling code here:
        boxDisc = ubigeoDAO.llenarcomboDist(((String) boxProv.getSelectedItem()));
        cboDistrito.setModel(boxDisc);
        txtUbigeo.setText(ubigeoDAO.getUbigeoByDeptProvDist(cboDepa.getSelectedItem().toString(), cboProv.getSelectedItem().toString(), cboDistrito.getSelectedItem().toString()));
        //   boxDisc = ubigeoDAO.llenarcomboDist(((ComboData) boxProv.getSelectedItem()).getText());
    }//GEN-LAST:event_cboProvItemStateChanged

    private void cboDistritoItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cboDistritoItemStateChanged
        // TODO add your handling code here:
        txtUbigeo.setText(ubigeoDAO.getUbigeoByDeptProvDist(cboDepa.getSelectedItem().toString(), cboProv.getSelectedItem().toString(), cboDistrito.getSelectedItem().toString()));
    }//GEN-LAST:event_cboDistritoItemStateChanged

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        // TODO add your handling code here:
        int id_cliente = Integer.parseInt(txtid.getText());
        if (clienteDAO.eliminar(id_cliente)) {
            tblCliente.setModel(clienteDAO.llenartabla());
            JOptionPane.showMessageDialog(this, "Cliente eliminado con éxito");
            limpiar();
        } else {
            JOptionPane.showMessageDialog(this, "No se puede eliminar Cliente");
        }
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        this.clienteDAO.ImprimirReporte();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void tblClienteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblClienteMouseClicked

        int selectedRow = tblCliente.getSelectedRow();
        if (selectedRow != -1) {
            // Obtener datos de la fila seleccionada
            int idCliente = Integer.parseInt((String) tblCliente.getValueAt(selectedRow, 0));
            //  String[] dt = ((String) jtblTrabajador.getValueAt(selectedRow, 1)).split("\\|");
            //ComboData puesto = new ComboData(Integer.parseInt(dt[0].toString().trim()), dt[1].toString().trim());
            String docIdent = (String) tblCliente.getValueAt(selectedRow, 1);
            String nombre = (String) tblCliente.getValueAt(selectedRow, 2);
            String ubigeo = (String) tblCliente.getValueAt(selectedRow, 3);

            //idCliente,nif,nombre,idUbigeo,direccion,celular,telefono,correo,estado
            Object[][] ubigeos = ubigeoDAO.getRowByIdUbigeo(ubigeo);
            cboDepa.setSelectedItem(ubigeos[0][1].toString());
            cboProv.setSelectedItem(ubigeos[0][2].toString());
            cboDistrito.setSelectedItem(ubigeos[0][3].toString());
            String direccion = (String) tblCliente.getValueAt(selectedRow, 4);
            String celular = (String) tblCliente.getValueAt(selectedRow, 5);
            String telefono = (String) tblCliente.getValueAt(selectedRow, 6);
            String correo = (String) tblCliente.getValueAt(selectedRow, 7);
            short estado = (short) (("Activo".equals(tblCliente.getValueAt(selectedRow, 8).toString())) ? 1 : 0);

            Cliente cliente = new Cliente(idCliente, docIdent, nombre, ubigeo, direccion, celular, telefono, correo, estado);
            setDataCliente(cliente);
            btnregistro.setText("Actualizar");
        }
    }//GEN-LAST:event_tblClienteMouseClicked

    private void cboBuscarItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cboBuscarItemStateChanged
        // TODO add your handling code here:
        String str = this.cboBuscar.getSelectedItem().toString();
        if (str.equals("TODOS")) {
            txtBuscador.setEnabled(false);
        } else {
            txtBuscador.setEnabled(true);
        }
    }//GEN-LAST:event_cboBuscarItemStateChanged

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:

        String buscar = cboBuscar.getSelectedItem().toString();
        switch (buscar) {
            case "TODOS":
                defaultTableModel = clienteDAO.llenartabla();
                break;
            case "DNI":
                defaultTableModel = clienteDAO.buscarEnTabla("nif", txtBuscador.getText());
                break;
            case "NOMBRE":
                defaultTableModel = clienteDAO.buscarEnTabla("nombre", txtBuscador.getText());
                break;
            case "TELEFONO":
                defaultTableModel = clienteDAO.buscarEnTabla("telefono", txtBuscador.getText());
                break;
            case "CELULAR":
                defaultTableModel = clienteDAO.buscarEnTabla("celular", txtBuscador.getText());
                break;
            default:
                throw new AssertionError();
        }
        tblCliente.setModel(defaultTableModel);
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEliminar;
    private javax.swing.ButtonGroup btnGrpEstado;
    private javax.swing.JButton btnNuevo;
    private javax.swing.JButton btnregistro;
    private javax.swing.JComboBox<String> cboBuscar;
    private javax.swing.JComboBox<String> cboDepa;
    private javax.swing.JComboBox<String> cboDistrito;
    private javax.swing.JComboBox<String> cboProv;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JRadioButton rbActivo;
    private javax.swing.JRadioButton rbInactivo;
    private javax.swing.JTable tblCliente;
    private javax.swing.JTextField txtBuscador;
    private javax.swing.JTextField txtCelular;
    private javax.swing.JTextField txtCorreo;
    private javax.swing.JTextField txtTelefono;
    private javax.swing.JTextField txtUbigeo;
    private javax.swing.JTextField txtdireccion;
    private javax.swing.JTextField txtid;
    private javax.swing.JTextField txtnombre;
    private javax.swing.JTextField txtnroDocumento;
    // End of variables declaration//GEN-END:variables
}
