/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package UI.internal;

import BEAN.ComboData;
import BEAN.Trabajador;
import DAO.Conexion;
import DAO.Impl.TrabajadorDAOImpl;
import DAO.Impl.UbigeoUtilDAOImpl;
import DAO.TrabajadorDAO;
import java.text.SimpleDateFormat;
import java.time.LocalDate;
import java.time.ZoneId;
import java.time.format.DateTimeFormatter;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.Enumeration;
import java.util.List;
import javax.swing.AbstractButton;
import javax.swing.ButtonGroup;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;
import javax.swing.table.DefaultTableModel;
import javax.swing.text.DateFormatter;
import DAO.UbigeoUtilDAO;
import UTIL.EmailOnlyDocument;
import UTIL.NumberOnlyDocument;
import UTIL.TextOnlyDocument;
import java.lang.reflect.Field;
import java.util.HashMap;
import java.util.Map;
import java.util.StringJoiner;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JTextField;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;

/**
 *
 * @author xhesm
 */
public class InFrmTrabajador extends javax.swing.JInternalFrame {

    /**
     * Creates new form InFrmTrabajador
     */
    TrabajadorDAO trabajadorDAO = new TrabajadorDAOImpl();
    UbigeoUtilDAO ubigeoDAO = new UbigeoUtilDAOImpl();

    DefaultTableModel defaultTableModel = new DefaultTableModel();
    Object[][] select, selectaux;
    DefaultComboBoxModel<ComboData> boxModel = null;
    DefaultComboBoxModel<String> boxDep, boxProv, boxDisc = null;

    public InFrmTrabajador() {
        initComponents();
        default_config();
        jtblTrabajador.setModel(trabajadorDAO.llenartabla());
        boxModel = trabajadorDAO.llenarcombo();
        config_ubigeo();
        default_validaciones();
    }

    public void default_config() {
        this.setTitle("Trabajador");
        this.setClosable(true);
        this.setResizable(true);
        this.txtBuscador.setEnabled(false);
    }

    public void config_ubigeo() {
        boxDep = ubigeoDAO.llenarcomboDep();
        cboPuesto.setModel(boxModel);
        cboDepa.setModel(boxDep);
        cboDepa.setSelectedIndex(2);
        txtUbigeo.setText(ubigeoDAO.getUbigeoByDeptProvDist(cboDepa.getSelectedItem().toString(), cboProv.getSelectedItem().toString(), cboDistrito.getSelectedItem().toString()));
    }

    public void default_validaciones() {
        txtCelular.setDocument(new NumberOnlyDocument(9));
        txtTelefono.setDocument(new NumberOnlyDocument(6));
        txtnroDocumento.setDocument(new NumberOnlyDocument(15));
        txtnombre.setDocument(new TextOnlyDocument(30));
        txtApePaterno.setDocument(new TextOnlyDocument(30));
        txtApeMaterno.setDocument(new TextOnlyDocument(30));
        txtdireccion.setDocument(new EmailOnlyDocument(60));
        txtCorreo.setDocument(new EmailOnlyDocument(60));
        rbActivo.setSelected(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnGrpEstado = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        txtnroDocumento = new javax.swing.JTextField();
        txtid = new javax.swing.JTextField();
        cboPuesto = new javax.swing.JComboBox<>();
        txtnombre = new javax.swing.JTextField();
        txtApeMaterno = new javax.swing.JTextField();
        txtApePaterno = new javax.swing.JTextField();
        txtUbigeo = new javax.swing.JTextField();
        txtdireccion = new javax.swing.JTextField();
        rbActivo = new javax.swing.JRadioButton();
        rbInactivo = new javax.swing.JRadioButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        cboGenero = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        txtFechaNacimiento = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txtCelular = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        txtTelefono = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        txtCorreo = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        btnNuevo = new javax.swing.JButton();
        btnregistro = new javax.swing.JButton();
        cboDepa = new javax.swing.JComboBox<>();
        jLabel14 = new javax.swing.JLabel();
        cboProv = new javax.swing.JComboBox<>();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        cboDistrito = new javax.swing.JComboBox<>();
        jLabel17 = new javax.swing.JLabel();
        btnEliminar = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtblTrabajador = new javax.swing.JTable();
        txtBuscador = new javax.swing.JTextField();
        cboBuscar = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));
        getContentPane().setLayout(new javax.swing.BoxLayout(getContentPane(), javax.swing.BoxLayout.PAGE_AXIS));

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Trabajador"));

        txtnroDocumento.setName("Nro Documento"); // NOI18N

        txtid.setEnabled(false);

        txtnombre.setName("Nombre"); // NOI18N

        txtApeMaterno.setName("Apellido Materno"); // NOI18N

        txtApePaterno.setName("Apellido Paterno"); // NOI18N

        txtUbigeo.setEnabled(false);
        txtUbigeo.setName("Ubigeo"); // NOI18N

        txtdireccion.setName("Dirección"); // NOI18N

        btnGrpEstado.add(rbActivo);
        rbActivo.setText("Activo");
        rbActivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbActivoActionPerformed(evt);
            }
        });

        btnGrpEstado.add(rbInactivo);
        rbInactivo.setText("Inactivo");
        rbInactivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbInactivoActionPerformed(evt);
            }
        });

        jLabel1.setText("Id");

        jLabel2.setText("Puesto");

        jLabel3.setText("Nombre");

        jLabel4.setText("Nro Documento");

        jLabel5.setText("Apellido Paterno");

        jLabel6.setText("Apellido Materno");

        jLabel7.setText("Ubigeo");

        jLabel8.setText("Género");

        cboGenero.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Femenino", "Masculino" }));

        jLabel9.setText("Dirección");

        txtFechaNacimiento.setName("Fecha Nacimiento"); // NOI18N
        txtFechaNacimiento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFechaNacimientoActionPerformed(evt);
            }
        });

        jLabel10.setText("Fecha Nacimiento");

        txtCelular.setName("Celular"); // NOI18N

        jLabel11.setText("Celular");

        txtTelefono.setName("Teléfono"); // NOI18N

        jLabel12.setText("Teléfono");

        txtCorreo.setName("Correo"); // NOI18N

        jLabel13.setText("Correo");

        btnNuevo.setText("Nuevo");
        btnNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevoActionPerformed(evt);
            }
        });

        btnregistro.setText("Registrar");
        btnregistro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnregistroActionPerformed(evt);
            }
        });

        cboDepa.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cboDepaItemStateChanged(evt);
            }
        });
        cboDepa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboDepaActionPerformed(evt);
            }
        });

        jLabel14.setText("Departamento");

        cboProv.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cboProvItemStateChanged(evt);
            }
        });

        jLabel15.setText("Provincia");

        jLabel16.setText("Distrito");

        cboDistrito.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cboDistritoItemStateChanged(evt);
            }
        });

        jLabel17.setText("Estado");

        btnEliminar.setText("Eliminar");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });

        jButton2.setText("Ver Reporte");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel1)
                                .addComponent(txtnroDocumento, javax.swing.GroupLayout.DEFAULT_SIZE, 192, Short.MAX_VALUE)
                                .addComponent(jLabel6)
                                .addComponent(txtApeMaterno, javax.swing.GroupLayout.DEFAULT_SIZE, 192, Short.MAX_VALUE)
                                .addComponent(jLabel5)
                                .addComponent(txtApePaterno, javax.swing.GroupLayout.DEFAULT_SIZE, 192, Short.MAX_VALUE)
                                .addComponent(jLabel4)
                                .addComponent(txtnombre, javax.swing.GroupLayout.DEFAULT_SIZE, 192, Short.MAX_VALUE)
                                .addComponent(jLabel3)
                                .addComponent(jLabel2)
                                .addComponent(txtid, javax.swing.GroupLayout.DEFAULT_SIZE, 192, Short.MAX_VALUE)
                                .addComponent(cboPuesto, 0, 192, Short.MAX_VALUE)
                                .addComponent(jLabel9)
                                .addComponent(txtdireccion))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel8)
                                .addComponent(cboGenero, 0, 194, Short.MAX_VALUE)))
                        .addGap(100, 100, 100)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel14)
                                .addComponent(jLabel16)
                                .addComponent(jLabel15)
                                .addComponent(cboDistrito, 0, 194, Short.MAX_VALUE)
                                .addComponent(cboProv, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(cboDepa, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(rbActivo)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(rbInactivo))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel13)
                                .addComponent(txtCorreo)
                                .addComponent(jLabel11)
                                .addComponent(jLabel12)
                                .addComponent(txtCelular)
                                .addComponent(txtTelefono)
                                .addComponent(txtFechaNacimiento, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel10))
                            .addComponent(jLabel17)
                            .addComponent(jLabel7)
                            .addComponent(txtUbigeo, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnNuevo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnregistro)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnEliminar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton2)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cboDepa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cboProv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cboPuesto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel16)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(2, 2, 2)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtnroDocumento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cboDistrito, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(1, 1, 1)
                        .addComponent(txtnombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addGap(5, 5, 5)
                        .addComponent(txtUbigeo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(2, 2, 2)
                        .addComponent(txtApePaterno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtApeMaterno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(txtdireccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel8)
                        .addGap(3, 3, 3)
                        .addComponent(cboGenero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addGap(1, 1, 1)
                        .addComponent(txtCelular, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel12)
                        .addGap(2, 2, 2)
                        .addComponent(txtTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel13)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(txtFechaNacimiento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel10))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel17)
                        .addGap(3, 3, 3)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(rbActivo)
                            .addComponent(rbInactivo))))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnNuevo)
                    .addComponent(btnregistro)
                    .addComponent(btnEliminar)
                    .addComponent(jButton2))
                .addContainerGap())
        );

        getContentPane().add(jPanel1);

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jtblTrabajador.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jtblTrabajador.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jtblTrabajador.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jtblTrabajador.setGridColor(new java.awt.Color(102, 204, 0));
        jtblTrabajador.setRowHeight(15);
        jtblTrabajador.setRowMargin(1);
        jtblTrabajador.setSelectionBackground(new java.awt.Color(102, 204, 0));
        jtblTrabajador.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jtblTrabajador.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtblTrabajadorMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jtblTrabajador);

        cboBuscar.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "TODOS", "DNI", "NOMBRE", "APELLIDO PATERNO", "APELLIDO MATERNO", "TELEFONO", "CELULAR" }));
        cboBuscar.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cboBuscarItemStateChanged(evt);
            }
        });

        jButton1.setText("Buscar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 552, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(cboBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtBuscador)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton1)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtBuscador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cboBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 283, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel2);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtFechaNacimientoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFechaNacimientoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFechaNacimientoActionPerformed

    private void btnNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevoActionPerformed
        limpiar();
    }//GEN-LAST:event_btnNuevoActionPerformed

    void limpiar() {
        txtApeMaterno.setText("");
        txtApePaterno.setText("");
        txtBuscador.setText("");
        txtCelular.setText("");
        txtCorreo.setText("");
        txtFechaNacimiento.setText("");
        txtTelefono.setText("");
        txtUbigeo.setText("");
        txtdireccion.setText("");
        txtid.setText("");
        txtnombre.setText("");
        txtnroDocumento.setText("");
        btnregistro.setText("Registrar");
    }

    void setDataTrabajador(Trabajador t, ComboData p) {
        txtApeMaterno.setText(t.getApeMat());
        txtApePaterno.setText(t.getApePat());
        int index = findIndex(boxModel, p);
        cboPuesto.setSelectedIndex(index);
        txtCelular.setText(t.getCelular());
        txtCorreo.setText(t.getCorreo());
        txtFechaNacimiento.setText(t.getFecha_nacimiento().toString());
        txtTelefono.setText(t.getTelefono());
        txtUbigeo.setText(t.getUbigeo());
        txtdireccion.setText(t.getDireccion());
        txtid.setText(t.getIdTrabajador() + "");
        txtnombre.setText(t.getNombre());
        txtnroDocumento.setText(t.getDocIdent());
        cboGenero.setSelectedIndex(t.getGenero());
        if (t.getEstado() == 1) {
            rbActivo.setSelected(true);
        } else {
            rbInactivo.setSelected(true);
        }
    }

    private static String getSelectedButtonValue(ButtonGroup buttonGroup) {
        for (Enumeration<AbstractButton> buttons = buttonGroup.getElements(); buttons.hasMoreElements();) {
            AbstractButton button = buttons.nextElement();
            if (button.isSelected()) {
                return button.getText();
            }
        }
        return null;
    }

    public boolean llenarError(JTextField... jTxtFields) {
        JPanel panel = new JPanel();
        StringJoiner joiner = new StringJoiner("<br>");
        for (JTextField jtxtfield : jTxtFields) {
            System.out.println("field" + jtxtfield.getName());
            if (jtxtfield.getText().isEmpty()) {
                joiner.add(jtxtfield.getName().concat(" no puede estar vacío"));
            }
        }
        if (!joiner.toString().isEmpty()) {
            panel.add(new JLabel("<html><font color='red'>" + joiner.toString() + "</font></html>"));
            JOptionPane.showOptionDialog(
                    null,
                    panel,
                    "Alerta",
                    JOptionPane.WARNING_MESSAGE,
                    JOptionPane.WARNING_MESSAGE,
                    null,
                    new Object[]{},
                    null
            );
        }
        return !joiner.toString().isEmpty();
    }

    private void btnregistroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnregistroActionPerformed
        // TODO add your handling code here:

        Trabajador t = new Trabajador();
        t.setDireccion(txtdireccion.getText());
        t.setNombre(txtnombre.getText());
        t.setApePat(txtApePaterno.getText());
        t.setApeMat(txtApeMaterno.getText());
        t.setCelular(txtCelular.getText());
        t.setCorreo(txtCorreo.getText());
        t.setGenero(cboGenero.getSelectedIndex());
        t.setUbigeo(txtUbigeo.getText());
        t.setDocIdent(txtnroDocumento.getText());
        t.setTelefono(txtTelefono.getText());
        t.setEstado((short) (rbActivo.isSelected() ? 1 : 0));
        boolean condicionerror
                = llenarError(
                        txtdireccion,
                        txtnombre,
                        txtApePaterno,
                        txtApeMaterno,
                        txtCelular,
                        txtCorreo,
                        txtUbigeo,
                        txtnroDocumento,
                        txtTelefono,
                        txtFechaNacimiento);

        if (!txtFechaNacimiento.getText().isEmpty()) {
            LocalDate localDate = LocalDate.parse(txtFechaNacimiento.getText());
            t.setFecha_nacimiento(localDate);
        }
        t.setIdPuesto(((ComboData) cboPuesto.getSelectedItem()).getId());
        System.out.println(this.btnregistro.getText());
        if (!condicionerror) {
            switch (this.btnregistro.getText()) {
                case "Registrar":
                    t.setIdTrabajador(0);
                    if (trabajadorDAO.save(t)) {
                        JOptionPane.showMessageDialog(this, "Trabajador Guardado Correctamente", "Mensaje de confirmación", JOptionPane.INFORMATION_MESSAGE);
                        jtblTrabajador.setModel(trabajadorDAO.llenartabla());
                    }
                    break;
                case "Actualizar":
                    t.setIdTrabajador(Integer.parseInt(txtid.getText()));
                    if (trabajadorDAO.save(t)) {
                        JOptionPane.showMessageDialog(this, "Trabajador Actualizado Correctamete", "Mensaje de confirmación", JOptionPane.INFORMATION_MESSAGE);
                        jtblTrabajador.setModel(trabajadorDAO.llenartabla());
                    }
                    break;
            }
        }

    }//GEN-LAST:event_btnregistroActionPerformed


    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here: 
        String buscar = cboBuscar.getSelectedItem().toString();
        switch (buscar) {
            case "TODOS":

                defaultTableModel = trabajadorDAO.llenartabla();
                break;
            case "DNI":
                defaultTableModel = trabajadorDAO.buscarEnTabla("docIdent", txtBuscador.getText());
                break;
            case "NOMBRE":
                defaultTableModel = trabajadorDAO.buscarEnTabla("nombre", txtBuscador.getText());
                break;
            case "APELLIDO PATERNO":
                defaultTableModel = trabajadorDAO.buscarEnTabla("apePat", txtBuscador.getText());
                break;
            case "APELLIDO MATERNO":
                defaultTableModel = trabajadorDAO.buscarEnTabla("apeMat", txtBuscador.getText());
                break;
            case "TELEFONO":
                defaultTableModel = trabajadorDAO.buscarEnTabla("telefono", txtBuscador.getText());
                break;
            case "CELULAR":
                defaultTableModel = trabajadorDAO.buscarEnTabla("celular", txtBuscador.getText());
                break;
            default:
                throw new AssertionError();
        }
        jtblTrabajador.setModel(defaultTableModel);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void cboBuscarItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cboBuscarItemStateChanged
        // TODO add your handling code here: 
        String str = this.cboBuscar.getSelectedItem().toString();
        if (str.equals("TODOS")) {
            txtBuscador.setEnabled(false);
        } else {
            txtBuscador.setEnabled(true);
        }
    }//GEN-LAST:event_cboBuscarItemStateChanged

    private static int findIndex(DefaultComboBoxModel<ComboData> model, ComboData value) {
        for (int i = 0; i < model.getSize(); i++) {
            if (model.getElementAt(i).getId() == (value.getId())) {
                return i;
            }
        }
        return -1;
    }

    private void jtblTrabajadorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtblTrabajadorMouseClicked

        int selectedRow = jtblTrabajador.getSelectedRow();
        if (selectedRow != -1) {
            // Obtener datos de la fila seleccionada
            int idTrabajador = Integer.parseInt((String) jtblTrabajador.getValueAt(selectedRow, 0));
            String[] dt = ((String) jtblTrabajador.getValueAt(selectedRow, 1)).split("\\|");
            ComboData puesto = new ComboData(Integer.parseInt(dt[0].toString().trim()), dt[1].toString().trim());
            String docIdent = (String) jtblTrabajador.getValueAt(selectedRow, 2);
            String nombre = (String) jtblTrabajador.getValueAt(selectedRow, 3);
            String apePat = (String) jtblTrabajador.getValueAt(selectedRow, 4);
            String apeMat = (String) jtblTrabajador.getValueAt(selectedRow, 5);
            String ubigeo = (String) jtblTrabajador.getValueAt(selectedRow, 6);

            Object[][] ubigeos = ubigeoDAO.getRowByIdUbigeo(ubigeo);
            cboDepa.setSelectedItem(ubigeos[0][1].toString());
            cboProv.setSelectedItem(ubigeos[0][2].toString());
            cboDistrito.setSelectedItem(ubigeos[0][3].toString());

            String direccion = (String) jtblTrabajador.getValueAt(selectedRow, 7);
            int genero = (int) (("Masculino".equals(jtblTrabajador.getValueAt(selectedRow, 8).toString())) ? 1 : 0);//Integer.parseInt((String) jtblTrabajador.getValueAt(selectedRow, 8));

            DateTimeFormatter formatter = DateTimeFormatter.ofPattern("yyyy-MM-dd");
            LocalDate fechaNacimiento = LocalDate.parse(jtblTrabajador.getValueAt(selectedRow, 9).toString(), formatter);

            String celular = (String) jtblTrabajador.getValueAt(selectedRow, 10);
            String telefono = (String) jtblTrabajador.getValueAt(selectedRow, 11);
            String correo = (String) jtblTrabajador.getValueAt(selectedRow, 12);
            short estado = (short) (("Activo".equals(jtblTrabajador.getValueAt(selectedRow, 13).toString())) ? 1 : 0);

            Trabajador trabajador = new Trabajador(idTrabajador, puesto.getId(), docIdent, nombre, apePat, apeMat,
                    ubigeo, direccion, genero, fechaNacimiento, celular, telefono, correo, estado);
            setDataTrabajador(trabajador, puesto);
            System.out.println(trabajador.toString());
            btnregistro.setText("Actualizar");
        }
    }//GEN-LAST:event_jtblTrabajadorMouseClicked

    private void rbActivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbActivoActionPerformed
        // TODO add your handling code here:
        String selectedValue = getSelectedButtonValue(btnGrpEstado);
        System.out.println(selectedValue);
    }//GEN-LAST:event_rbActivoActionPerformed

    private void rbInactivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbInactivoActionPerformed
        // TODO add your handling code here:
        String selectedValue = getSelectedButtonValue(btnGrpEstado);
        System.out.println(selectedValue);
    }//GEN-LAST:event_rbInactivoActionPerformed

    private void cboDepaItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cboDepaItemStateChanged
        // TODO add your handling code here:

        boxProv = ubigeoDAO.llenarcomboProv((String) boxDep.getSelectedItem());
        cboProv.setModel(boxProv);
        boxDisc = ubigeoDAO.llenarcomboDist((String) boxProv.getSelectedItem());
        cboDistrito.setModel(boxDisc);
        txtUbigeo.setText(ubigeoDAO.getUbigeoByDeptProvDist(cboDepa.getSelectedItem().toString(), cboProv.getSelectedItem().toString(), cboDistrito.getSelectedItem().toString()));
// boxProv = ubigeoDAO.llenarcomboProv(((ComboData) boxDep.getSelectedItem()).getText());
    }//GEN-LAST:event_cboDepaItemStateChanged

    private void cboProvItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cboProvItemStateChanged
        // TODO add your handling code here:
        boxDisc = ubigeoDAO.llenarcomboDist(((String) boxProv.getSelectedItem()));
        cboDistrito.setModel(boxDisc);
        txtUbigeo.setText(ubigeoDAO.getUbigeoByDeptProvDist(cboDepa.getSelectedItem().toString(), cboProv.getSelectedItem().toString(), cboDistrito.getSelectedItem().toString()));
//   boxDisc = ubigeoDAO.llenarcomboDist(((ComboData) boxProv.getSelectedItem()).getText());
    }//GEN-LAST:event_cboProvItemStateChanged

    private void cboDepaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboDepaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cboDepaActionPerformed

    private void cboDistritoItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cboDistritoItemStateChanged
        // TODO add your handling code here:
        txtUbigeo.setText(ubigeoDAO.getUbigeoByDeptProvDist(cboDepa.getSelectedItem().toString(), cboProv.getSelectedItem().toString(), cboDistrito.getSelectedItem().toString()));
    }//GEN-LAST:event_cboDistritoItemStateChanged

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here: 
        this.trabajadorDAO.ImprimirReporte();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        // TODO add your handling code here:


    }//GEN-LAST:event_btnEliminarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEliminar;
    private javax.swing.ButtonGroup btnGrpEstado;
    private javax.swing.JButton btnNuevo;
    private javax.swing.JButton btnregistro;
    private javax.swing.JComboBox<String> cboBuscar;
    private javax.swing.JComboBox<String> cboDepa;
    private javax.swing.JComboBox<String> cboDistrito;
    private javax.swing.JComboBox<String> cboGenero;
    private javax.swing.JComboBox<String> cboProv;
    private javax.swing.JComboBox<ComboData> cboPuesto;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jtblTrabajador;
    private javax.swing.JRadioButton rbActivo;
    private javax.swing.JRadioButton rbInactivo;
    private javax.swing.JTextField txtApeMaterno;
    private javax.swing.JTextField txtApePaterno;
    private javax.swing.JTextField txtBuscador;
    private javax.swing.JTextField txtCelular;
    private javax.swing.JTextField txtCorreo;
    private javax.swing.JTextField txtFechaNacimiento;
    private javax.swing.JTextField txtTelefono;
    private javax.swing.JTextField txtUbigeo;
    private javax.swing.JTextField txtdireccion;
    private javax.swing.JTextField txtid;
    private javax.swing.JTextField txtnombre;
    private javax.swing.JTextField txtnroDocumento;
    // End of variables declaration//GEN-END:variables
}
